### ISSUE TITLE
Update PR base branch when killing a branch

### ISSUE THREAD

**Issue by martinjaime** [git-town/git-town#1036]
Had the branch ancestry:
```
branch-1
  branch-2-bug-fix
    branch-3
```
All three branches had an open PR. `branch-2-bug-fix`‘s PR was a duplicate of a fix that someone else had already put in and merged at the same time. I closed the PR on `branch-2-bug-fix` and ran `git town kill` on that branch. 

I was expecting it to change the base branch of `branch-3`‘s PR but instead it closed it.

**Comment by charlierudolph** [comment]
For Github, we already have all the necessary code there and should be able to just it up. In `kill` we will need to check for a code hosting driver (similar to ship), and if the there are PRs into the parent, update the base branch of those PRs before killing the branch.

Really opening the door on github integration now. PRs are such a major part of our process though its definitely worth it.

**Comment by kevgo** [comment]
Definitely a missing feature now that we can update Github PRs.

**Comment by kevgo** [comment]
This is now available in [v16.3](https://github.com/git-town/git-town/releases/tag/v16.3.0).
