### ISSUE TITLE
Shipping a branch does not close GitLab MR

### ISSUE THREAD

**Issue by qrevel** [git-town/git-town#1092]
When using `git town ship` with a GitLab repo, the MR is not merged and the branch is deleted.
The MR stays opened because it can't be merged (the code has already been merged but the MR doesn't know it) and it can be closed but that's not what really happened.

Squash MR is not available for GitLab. They provide a [Squash and Merge](https://gitlab.com/help/user/project/merge_requests/squash_and_merge) feature on the Web UI and it is only for GitLab EES.  All the commits are squashed in one and then a non fast forward merge is applied on the remaining commit.

I've also looked up inside [GitLab API](https://docs.gitlab.com/ce/api/merge_requests.html#accept-mr), it is actually not possible to squash MR throught API.

Do you have any idea to update the MR status to merged with git town ship?

Thanks

**Comment by charlierudolph** [comment]
No idea what we could actually do here. The limitation of the Gitlab API is not something we can control or workaround.

**Comment by qrevel** [comment]
Maybe we could have an option to use ff merge instead of squash and merge.
GitLab may be able to keep up.

**Comment by kevgo** [comment]
I think adding an option to ship by squashing all commits in the branch and then do a `--no-ff` merge into the main branch could make sense for Git Town.

Since the current Git Town team doesn't have access to a GitLab server for testing, it will be hard for us to build this but we are willing to accept a pull request that implements this behavior.

**Comment by qrevel** [comment]
Yesterday, GitLab released [Squash and merge](https://about.gitlab.com/2018/06/22/gitlab-11-0-released/#squash-and-merge-in-gitlab-core-and-gitlabcom-free) strategy for everyone in the 11.0 version.

GitLab API now allows to [create MR](https://docs.gitlab.com/ce/api/merge_requests.html#create-mr) that will squash commits before merge.

Could it be possible to integrate Git Town with GitLab?

**Comment by kevgo** [comment]
Hey @qrevel, that's very exciting! Git Town is already integrated with GitLab. See the [Gitlab driver](https://github.com/Originate/git-town/blob/master/src/drivers/gitlab.go).

If there is a new API on GitLab that allows better shipping via merge requests, let's definitely bring it into Git Town. This would be relatively easy to build, similar to the already existing Github integration. See its [documentation](https://github.com/Originate/git-town/blob/master/documentation/commands/ship.md#github-pull-request-integration) and [source code](https://github.com/Originate/git-town/blob/master/src/drivers/github.go) for details on how this works.

Pull requests adopting a similar strategy for GitLab are welcome!
