### ISSUE TITLE
Error when using git-town ship

### ISSUE THREAD

**Issue by hmbrg** [git-town/git-town#1097]
```
[master] git merge --squash somebranch
fatal: You cannot combine --squash with --no-ff.
2018/01/20 23:54:18 Error squash merging: exit status 128
```

This happens every time, no matter what the project is. What am I doing wrong?

**Comment by kevgo** [comment]
Hey @brighthero, Git Town doesn't use the `--no-ff` option when shipping, see [the end-to-end test for it](https://github.com/Originate/git-town/blob/master/features/git-town-ship/current_branch/on_feature_branch/without_open_changes/with_tracking_branch.feature#L27). This must somehow come from your Git configuration. Can you please post the exact command you are running, as well as the full screen output Git Town produces? Also, what is the output when you run `git config -l` (please scrub sensitive data before posting that output here).

**Comment by charlierudolph** [comment]
Confirmed this happens when a user has the [`merge.ff`](https://git-scm.com/docs/git-merge#git-merge-mergeff) option set to false. I think this is a bug in git as that should not be added when squash merging

**Comment by charlierudolph** [comment]
Found a discussion of the bug in the git mailing list: https://public-inbox.org/git/CAHd499C=3Y-ykgYZhSJzk=e-Pi6BUFeN8C89krd5T7T5fRB91g@mail.gmail.com/

**Comment by charlierudolph** [comment]
Also confirmed this is still happening on git 2.17.0 even though the discussion is quite old

**Comment by kevgo** [comment]
That same email thread suggests providing `--ff` to the squash command in order to override the Git configuration, which shouldn't apply in this case anyways. So, this squash command should work in all cases:

```
git merge --squash --ff <feature branch name>
```
