### ISSUE TITLE
update parent command

### ISSUE THREAD

**Issue by charlierudolph** [git-town/git-town#1165]
Not sure on the need of this but I have sometimes wanted to switch a branches parent and wanted all unique commits on that branch (relative to its current branch) cherry-picked onto the new parent. 

Not certain if merge conflict resolutions would get carried over in this case or not.

**Comment by kevgo** [comment]
I think this should be the default behavior. When I change the parent of the branch, I also always want that the commits I made are moved over to a new branch that starts at the new branch. I think we can simply rebase the current branch against the new parent and change the Git Town config.

**Comment by kevgo** [comment]
I think this is implemented in the form of the [set-parent](https://www.git-town.com/commands/set-parent) command.
