### ISSUE TITLE
API access for GitHub Enterprise

### ISSUE THREAD

**Issue by ericyliu** [git-town/git-town#1179]
When running `git-town ship` with a personal access token, it tries to run `git fetch` on the host `https://api.github.com`. Setting `git-town.code-hosting-origin-hostname` does not affect this.

**Comment by kevgo** [comment]
To tell the GitHub driver about the custom URLs for GitHub Enterprise, we need to instantiate it differently. Instead of:

```go
github.NewClient(httpClient)
```

we need to run 

```go
github.NewClient(httpClient).WithEnterpriseURLs(baseURL, uploadURL)
```

**Comment by kevgo** [comment]
Closing this ticket since all the feedback and information provided in it has been addressed. This doesn't mean that GitHub Enterprise support will work perfectly. If there is additional feedback, please provide it as a new ticket.
