### ISSUE TITLE
Never Merge Commit?

### ISSUE THREAD

**Issue by Iron-Ham** [git-town/git-town#1189]
Is there any mechanism in Git-Town to disallow _all_ merge commits and globally prefer rebasing _in all scenarios_? My `pull-branch-strategy` has been set to `rebase`, but I've been getting merge commits in my branches even with this setting toggled.

**Comment by charlierudolph** [comment]
Not currently. The pull branch strategy only effects the main branch / perennial branches. Merging will always occur on feature branches. 

#1156 may be related to what you are asking for
