### ISSUE TITLE
Suggestion: add git-town alias library to oh-my-zsh

### ISSUE THREAD

**Issue by joshRpowell** [git-town/git-town#1208]
Hi, git-town user for 3+ years.  Also, use oh-my-zsh and thought to open a library as one doesn't exist. WIP PR here - https://github.com/robbyrussell/oh-my-zsh/pull/7989

Reaching out for suggestions/thoughts.

**Comment by kevgo** [comment]
This is awesome! Thanks for letting us know @joshRpowell! I like the shortcuts you define. When this is merged and shipped by oh-my-zsh, can you let us know or add a PR that adds this to the [installation instructions](https://github.com/Originate/git-town/blob/master/website/install.md)?

**Comment by joshRpowell** [comment]
Thanks @kevgo! Glad to help cut down on keystrokes where I can.  For the install instruction PR, are you thinking a separate subsection similar to [new releases](https://github.com/Originate/git-town/blob/master/website/install.md#notifications-about-new-releases)?

**Comment by kevgo** [comment]
@joshRpowell since we now support several shells, that seems like the best way to go. Thanks!

**Comment by joshRpowell** [comment]
@kevgo dusting this off and noticed this in oh-my-zsh [docs](https://github.com/ohmyzsh/ohmyzsh/blob/master/CONTRIBUTING.md#you-have-an-addition)
>For any extensive change, eg a new plugin, you will have to find testers to +1 your PR

anyone on the git-town team to test?

**Comment by kevgo** [comment]
Sorry I don't use zsh. @charlierudolph do you use it and can test this change?

**Comment by alexw10** [comment]
I can test it! I use oh-my-zsh and git town :)

**Comment by blaggacao** [comment]
Addressed by #1482
