### ISSUE TITLE
"git town shipped" command

### ISSUE THREAD

**Issue by kevgo** [git-town/git-town#1209]
A lot of people have the workflow to develop using Git Town but ship via a different means, for example by merging using the GitHub UI. These use cases would benefit from a systematic cleanup routine that could be implemented via this Bash file:

```shell
# remove all shipped branches
git town prune-branches  
git checkout master
git town sync
git checkout <branch we were on before>
```

This Bash file, however, fetches twice, making it slow. It seems better to create a new command `git town shipped` for this.

**Comment by charlierudolph** [comment]
Thoughts on having the ability to prune-branches as a part of sync? This could be controlled via a flag and config option. I think that'd be what I'd prefer.

**Comment by kevgo** [comment]
I like the idea, especially since there wouldn't be a performance impact. Right now synching a shipped branch re-pushes the branch to the remote. The new behavior would do the opposite: delete the local branch. If we hide this behind a flag for now, it wouldn't be a breaking change until we make this the default behavior.

Possible flag name: `prune-sync`.

**Comment by kevgo** [comment]
Another scenario where a "git town shipped" command might be useful is finding branches that are empty and deleting them locally and on the remote. This is relevant for situations where branches get shipped on the remote without deleting the remote branch. This can happen for a variety of reasons:

- the person doing the merge forgot or was unaware that they should delete the branch
- the person doing the merge wasn't permitted to delete the branch (happens in PRs from forked repos)
- the person doing the merge was unsure whether the shipped branch is still needed while reviewing and merging the code on a web UI
- misconfiguration of the source code platform resulted in branches not getting deleted after being shipped

The "shipped" command would do these things:

- delete branches that were deleted on the remote
- for each local branch:
  - sync the branch
  - run `git diff <main branch>`
  - if the diff is empty: kill the branch

This would also implement https://github.com/git-town/git-town/issues/765 for remotely shipped branches.

I think the "sync" command should never delete empty branches. This would interfere with the scenario where one starts working on a branch and syncs it before making the first commit. Such a behavior would make the "sync" command potentially dangerous. I prefer that the sync command remains a no-brainer that one can run fearlessly at any time without risking data loss.

I think a separate command just for deleting empty branches is too limited in its usability because it doesn't conver the scenario of cleaning up branches that got deleted remotely. A "shipped" command that handles all ways of cleaning up shipped branches and syncs the local workspace fills an important.

This new "shipped" command would - for the most part - replace the "prune-branches" command because it is a superset of the prune-branches command.
The new "shipped" command would only apply to all branches. There is no "shipped" command for individual branches.

**Comment by kevgo** [comment]
Dropping this idea in favor of https://github.com/git-town/git-town/issues/2026.
