### ISSUE TITLE
Ship command fails if "Automatically delete head branches" is enabled

### ISSUE THREAD

**Issue by alphatroya** [git-town/git-town#1210]
Github released new settings option [today](https://github.blog/changelog/2019-07-31-automatically-delete-head-branches-of-pull-requests). If enabled GH automatically remove PR branch and this is break up correct ship command execution.

**Comment by kevgo** [comment]
Could use https://github.com/Originate/git-town/pull/1219 as a template to add a `skip-delete-remote-branch` configuration setting that defaults to `false`.

**Comment by alphatroya** [comment]
Well, I think it resolve this issue. Thanks!

**Comment by kevgo** [comment]
No it doesn't. This is just a template for a fix to come. Thanks!  :)
