### ISSUE TITLE
Visual Studio Code Extension

### ISSUE THREAD

**Issue by sheldonhull** [git-town/git-town#1284]
A feature request, which might be a good case for me to learn some typescript 😀

As Visual Studio Code is used by many for development work, having integration into the workflow without cli interaction could help promote further adoption of this great tool. 

Suggest consider Visual Studio Code Extension for setup, default settings, and running actions through git town. Would be a pretty great way to encourage better workflow standards and make it even more approachable.

**Comment by kevgo** [comment]
Good idea. I also use VSCode and love it. Such an extension would have to support the entire flow, including asking the user for the branch name when hacking, resolving conflicts while syncing, etc. The good news is that VSCode already provides all the UI components for this. The Git Town maintainers are probably not going to get around to this, so if you want to take a stab at it, go ahead. TypeScript is easy and awesome enough that you will be able to pick it up in a day or two!

**Comment by sheldonhull** [comment]
I'm currently just using the console in vscode to do this. I think having an extension would be useful if just to launch the commands for newer users but not critical I guess. I just need to work up a Choco package for installing :-)

**Comment by kevgo** [comment]
minimal feature set:

- hack
- sync (the current branch, all branches)
  - continue
  - abort
- prune-branches
- edit [config file](https://github.com/git-town/git-town/issues/1030)

**Comment by kevgo** [comment]
A Git Town VSCode extension is an excellent idea! However, to keep this issue tracker focused on the CLI tool itself, I think this concept would be better served as a separate, standalone project with its own dedicated repository.

At this time, I don’t foresee progress on this idea unless it comes as an external contribution. To maintain focus and keep the tickets in this repo actionable, I’ll close this issue for now.

That said, if anyone is interested in spearheading the development of the extension, don't hesitate to reach out. I’d be happy to create a repository for it under https://github.com/git-town/vscode to help get things started.

Excited to see where this idea could lead in the future!
