### ISSUE TITLE
Fish completion overrides existing completion

### ISSUE THREAD

**Issue by sgarfinkel** [git-town/git-town#1302]
The installed fish completion eats all `git` expansions, but instead it should delegate anything that isn't `git town <command>` to the preinstalled git completion.

I'm not an expert on fish completions so I'm not sure how to resolve this myself, but currently you can't have completions for both `git` and `git town` concurrently.

**Comment by blaggacao** [comment]
The cli library's [cobra](https://github.com/spf13/cobra) upstream implementation should solve this: https://github.com/git-town/git-town/pull/1492
