### ISSUE TITLE
Add --dry-run flag to all commands

### ISSUE THREAD

**Issue by WurmD** [git-town/git-town#1303]
There currently is the --debug flag that prints all the commands ran, but still runs them.

If possible, it would be a treat to have the --dry-run flag on this command as well

**Comment by kevgo** [comment]
Thanks for the suggestion! You are right, the only command that supports `--dry-run` is `git town sync` right now. Adding this as a feature request, but setting the expectation that we probably won't get to this in a while.

Guideline to implement this:

- [define the flag for a Git Town command](https://github.com/git-town/git-town/blob/master/src/cmd/sync.go#L102)
- [parse and activate flag in a Git Town command](https://github.com/git-town/git-town/blob/master/src/cmd/sync.go#L60)
- [create feature spec for the command with dry-run enabled](https://github.com/git-town/git-town/blob/master/features/git-town-sync/current_branch/feature_branch/dry_run.feature) and run it to see if any unwanted commands get executed
- if commands get executed that shouldn't, disable them conditionally in step implementations similar to how it is done [here](https://github.com/git-town/git-town/blob/master/src/steps/push_branch_step.go#L28)

**Comment by kevgo** [comment]
This is implemented now.
