### ISSUE TITLE
Show pull request URL if we couldn't open a browser

### ISSUE THREAD

**Issue by tallpants** [git-town/git-town#1317]
Currently we exit with an error message if we couldn't find a browser to open:

https://github.com/Originate/git-town/blob/d1e9a2e5f9d9a292c8c5458d4a6960796912c88c/src/browsers/browsers.go#L26

I think we should print the pull request URL alongside it so the user can manually open it.

My use case is that I'm using git-town on a remote machine that I'm developing on through SSH. When I try to open a new pull request, I get this error message, but if it printed the URL to the console, then I could copy it and paste it into a browser on my local machine.

I can open a pull request for this, but I'm not sure how you'd like it to be structured. I think the simplest thing to do would be in `git-town/src/script/script.go`, change `OpenBrowser` func to be:

```go
// OpenBrowser opens the default browser with the given URL.
func OpenBrowser(url string) {
        fmt.Printf("Pull request URL: %s\n", url)
	command := browsers.GetOpenBrowserCommand()
	err := RunCommand(command, url)
	if err != nil {
		panic(err)
	}
}
```

If that sounds like an okay solution to you, let me know and I'll open a PR. Or if you could explain how you prefer it to be structured, I'll do that instead

**Comment by tallpants** [comment]
tagging @kevgo

**Comment by kevgo** [comment]
Hi @tallpants, so cool that you use Git Town for remote development! Your change sounds good. Please send a pull request! 🙂

**Comment by tallpants** [comment]
Awesome! Here you go! https://github.com/Originate/git-town/pull/1318
