### ISSUE TITLE
Enable replacing `xdg-open` with `wsl-open`

### ISSUE THREAD

**Issue by ericis** [git-town/git-town#1344]
When running on Windows Subsystem for Linux (WSL), executing `git town repo` and `git town new-pull-request` fails to open the web browser, because `xdg-open` wasn't designed for this environment. However, [`wsl-open`](https://github.com/4U6U57/wsl-open) works.

I attempted to alias `xdg-open` to `wsl-open`, including modifying my `~/.bashrc` file with an alias, but `git-town` seems to always use `xdg-open`.

Is swapping the tooling something `git-town` would enable, or should this entirely be fixed by the `xdg-open` team?

I'm open to this being user error somehow 👍 

**Command Log**

```bash
$ git new-pull-request

[my-branch] git fetch --prune --tags

[my-branch] git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.

[master] git rebase origin/master
Current branch master is up to date.

[master] git fetch upstream master
From https://[private-ghe-url]/[org]/[repo]
 * branch            master     -> FETCH_HEAD

[master] git rebase upstream/master
Current branch master is up to date.

[master] git checkout my-branch
Switched to branch 'my-branch'
Your branch is up to date with 'origin/my-branch'.

[my-branch] git merge --no-edit origin/my-branch
Already up to date.

[my-branch] git merge --no-edit master
Already up to date.

xdg-open https://[private-ghe-url]/[my-id]/[repo]/compare/365435%2Fnode-version?expand=1
/usr/bin/www-browser: line 121: /c/Windows/System32/reg.exe: No such file or directory
/usr/bin/www-browser: line 98: /c/Windows/System32/chcp.com: No such file or directory
/usr/bin/www-browser: line 103: /c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe: No such file or directory
/usr/bin/www-browser: line 98: /c/Windows/System32/chcp.com: No such file or directory
find: '/mnt/c/Microsoft/WindowsApps/': No such file or directory
/usr/bin/www-browser: line 98: /c/Windows/System32/chcp.com: No such file or directory
/usr/bin/www-browser: line 103: /c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe: No such file or directory
/usr/bin/www-browser: line 98: /c/Windows/System32/chcp.com: No such file or directory
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: elinks: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: lynx: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: w3m: not found
xdg-open: no method available for opening 'https://[private-ghe-url]/[my-id]/[repo]/compare/my-branch?expand=1'
2020/04/30 09:58:03 exit status 3
```

**Comment by kevgo** [comment]
Thanks for reporting this, @ericis, and cool to know that Git Town is used in WSL! I have and shipped #1347 to run `wsl-open` if it exists before trying `xdg-open` but cannot test it. Do you have a chance to install Git Town from source to verify if it works before I release this?

**Comment by ericis** [comment]
Apologies for the delay @kevgo. It mostly works and it's definately better, since it can work now instead of failing :100: 

I forked and cloned the source, (had to install `go` and `python2`).

## Test Results

| Status | Test | Notes |
| -------- | ------ | -------- |
| :-1:     | default WSL install | fails |
| :+1:  :-1:  | hack with `X display`, without `wsl-open` | see "X display hack" below |
| :1st_place_medal: | with `npm i -g wsl-open` | after building and running from source with this change |
| :+1: :thinking: | hack with `X display`, without `wsl-open`, inside Remote Desktop with [`xrdp` + `xfce4`](https://github.com/ericis/my-tools#wsl-and-xfce4-and-xrdp) | this kind-of works, but opens a browser in Windows host rather than in the remote desktop session |
| :-1: | with `npm i -g wsl-open`, inside Remote Desktop with [`xrdp` + `xfce4`](https://github.com/ericis/my-tools#wsl-and-xfce4-and-xrdp) | see "`wsl-open` inside Remote Desktop" below |

## Remaining Challenges

### X display hack

It looks like official GUI support is [on its way](https://github.com/microsoft/WSL/issues/938) sometime in the future. Until then, a lot of creative solutions exist to support GUI apps.

Before `wsl-open` support, I had found a hack work-around with `XLauncher` by adding this to `~/.bashrc`:

```
# https://nickjanetakis.com/blog/using-wsl-and-mobaxterm-to-create-a-linux-dev-environment-on-windows
export DISPLAY="$(/sbin/ip route | awk '/default/ { print $3 }'):0"
```

This hack **actually works** (without `wsl-open`), but has the nasty output below. You'll see that it's very similar to the original error, but finally attempts X display at the end with an error that actually ends up launching a browser on Windows host.

```
$ ./git-town repo

xdg-open https://github.com/ericis/git-town
Unable to init server: Broadway display type not supported: 172.24.128.1:0
Error: cannot open display: 172.24.128.1:0
[30965:30965:0815/203159.386107:ERROR:browser_main_loop.cc(1469)] Unable to open X display.
[0815/203159.401614:ERROR:nacl_helper_linux.cc(308)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly
Unable to init server: Broadway display type not supported: 172.24.128.1:0
Error: cannot open display: 172.24.128.1:0
/usr/bin/xdg-open: 869: iceweasel: not found
/usr/bin/xdg-open: 869: seamonkey: not found
/usr/bin/xdg-open: 869: mozilla: not found
/usr/bin/xdg-open: 869: epiphany: not found
/usr/bin/xdg-open: 869: konqueror: not found
/usr/bin/xdg-open: 869: chromium: not found
/usr/bin/xdg-open: 869: chromium-browser: not found
[31012:31012:0815/203200.061159:ERROR:browser_main_loop.cc(1469)] Unable to open X display.
[0815/203200.079096:ERROR:nacl_helper_linux.cc(308)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly
```

### `wsl-open` inside Remote Desktop

This completely fails inside of Remote Desktop with `wsl-open` installed, even with the X display hack. But, I believe this error is actually a `wsl-open` issue, not related to your change.

```
/home/iseric/.nvm/versions/node/v14.4.0/bin/wsl-open: line 241: powershell.exe: command not found
Please open in a browser: https://github.com/ericis/git-town
```

[See this GitLab issue](https://gitlab.com/4U6U57/wsl-open/-/issues/19) for more details.

**Comment by ericis** [comment]
@kevgo let me know if you'd like me to simply close this issue since it kind of works, open other issues, or leave this open. I'm honestly okay with any of those since I can make this work now.

**Comment by kevgo** [comment]
Sorry for the delay and thanks for the detailed testing! Since this ticket is for replacing `xdg-open` with `wsl-open`, and that has been shipped, let's close this ticket. I have documented that `wsl-open` needs to be installed in #1645. Please open additional tickets if there are other things Git Town can do to work better on WSL.
