### ISSUE TITLE
Feature request: set-parent-branch should also update the base branch of the associated PR

### ISSUE THREAD

**Issue by cirego** [git-town/git-town#1367]
I haven't verified this behavior if using `git town prepend`, but I have verified this behavior using `git town set-parent-branch`. If you have a branch that already has an open PR to master, then running `git town set-parent-branch` (or `sync`? my command history is gone...) will update the branch in GitHub. However, the base branch of the PR will still be the old parent branch, thereby making the PR appear to change more than it actually does.

Why change the parent branch on an existing PR? One might want to change the parent branch for an existing PR because because it's a draft or one received review feedback that one felt like should be a new PR.

Kevgo, thanks again for all the work you put into `git-town`. I'm finally hoping to spend a little time tomorrow playing around with opening these as PRs instead of opening issues for you!

**Comment by kevgo** [comment]
If this is what you mean, you are right: `git town set-parent-branch` should update the base branch of an open pull request for that branch on GitHub. Right now it doesn't do that, see the [source](https://github.com/git-town/git-town/blob/master/src/cmd/set_parent_branch.go#L27-L34) for details. This sounds like a missing feature. Thanks for the suggestion!

All the code to talk to the GitHub API is in [github.go](https://github.com/git-town/git-town/blob/master/src/drivers/github.go). There are drivers for many code hosting providers in this directory, they all implement the [CodeHostingDriver](https://github.com/git-town/git-town/blob/master/src/drivers/code_hosting_driver.go) interface.

**Comment by kevgo** [comment]
merging this ticket into #2745

**Comment by kevgo** [comment]
This is now available in [v16.3](https://github.com/git-town/git-town/releases/tag/v16.3.0).
