### ISSUE TITLE
Feature request: Show diff against parent branch in CLI

### ISSUE THREAD

**Issue by cirego** [git-town/git-town#1380]
This one is a small feature request. I know that I can run `git diff <parent>..HEAD` to see the changes between my branch and the parent branch. However, sometimes the parent branch is annoying to type and/or lookup. It would be great to have a convenience command  to show the delta. Perhaps something like `git town diff-parent`?

**Comment by kevgo** [comment]
That's a great idea! I regularly review changes on the terminal as well. Making sure that our users don't have to think about the branch setup and type cryptic low-level Git commands is exactly what Git Town is all about.

This is super easy to implement:

- create a new `diff-parent` folder in [features](https://github.com/git-town/git-town/tree/master/features) and add feature specs for the various use cases (diffing a feature branch, diffing a child branch, diffing a perennial branch, diffing a branch with unknown parent). This will look pretty similar to the [kill specs](https://github.com/git-town/git-town/tree/master/features/git-town-kill/current_branch/on_feature_branch).
- create a new file in [cmd](https://github.com/git-town/git-town/tree/master/src/cmd). For the content, one could imitate what the [main_branch command](https://github.com/git-town/git-town/blob/master/src/cmd/main_branch.go) does.

**Comment by kevgo** [comment]
This was implemented in #1385.
