### ISSUE TITLE
merge the three existing Git drivers into GitRepository

### ISSUE THREAD

**Issue by kevgo** [git-town/git-town#1390]
The current codebase contains three redundant packages that call Git. (1) Tests call Git commands using [GitRepository](https://github.com/git-town/git-town/blob/master/test/git_repository.go) instances. (2) Business logic runs important Git commands (that show up in console output) by calling static functions in the [script](https://github.com/git-town/git-town/tree/master/src/script) package. (3) Supplementary Git commands (that don't show up in the output) are run by calling static functions in the [git](https://github.com/git-town/git-town/tree/master/src/git) package. An example for (2) and (3) is [here](https://github.com/git-town/git-town/blob/master/src/steps/merge_branch_step.go#L33-L34).

(2) and (3) are a legacy from porting the original Bash implementation to Go. By reaching out on their own to acquire what they need instead of asking for what they need, they break the best practice of [dependency injection](http://mrclay.org/2014/04/06/dependency-injection-ask-for-what-you-need). This makes the business logic hard to test in anything smaller than end-to-end tests.

Another factor that is important to understand this proposal is that `GitRepository` doesn't run Git commands directly. It uses an injected instance of the [Shell](https://github.com/git-town/git-town/blob/master/src/command/shell.go) interface to run Git commands.

A solution to solve all problems mentioned above is to use `GitRepository` instances for all three use cases:
- Tests run Git commands by calling methods on a `GitRepository` instance that uses a [MockingShell](https://github.com/git-town/git-town/blob/master/test/mocking_shell.go) instance. This `Shell` instance runs the Git commands in a test directory, using a customized environment. This exists already.
- Important Git commands (2) use a `GitRepository` instance with a to be created `LoggingShell` instance. This `Shell` instance runs the given Git commands in the current directory and prints the Git commands run as well as their output.
- Supplementary Git commands (3) use a `GitRepository` instance with a [ShellInCurrentDir](https://github.com/git-town/git-town/blob/master/src/command/shell_in_current_dir.go) instance. This `Shell` instance just runs the given Git commands.

Besides reducing duplication, the proposed architecture allows unit-testing larger parts of the internal business logic without the need for additional tooling like [Dig](https://github.com/uber-go/dig) that feels un-idiomatic and invasive.

Open questions:

- How do we make the `GitRepository` instances available to business logic in step implementations in (2) and (3)?

**Comment by charlierudolph** [comment]
I like it. Hmm injecting the repository into steps could be possible by passing it to the main functions? Or maybe something what we are doing with the drivers folder with the activeDriver?

**Comment by kevgo** [comment]
I was also thinking about global function like `git.Logging()` and `git.Silent()`, which would be similar to [drivers.GetActiveDriver](https://github.com/git-town/git-town/blob/master/src/drivers/core.go#L11-L24) but return `GitRepository` instances. These functions would return a different instance in tests than in production. What bothers me about this setup is that this still feels too much like the [Singleton pattern](https://en.wikipedia.org/wiki/Singleton_pattern). 

A way to avoid the Singleton pattern and make the business logic more pure and testable would be to inject `GitRepository` instances directly into anybody  who needs them. In this case the [NoOpSteps](https://github.com/git-town/git-town/blob/master/src/steps/no_op_step.go#L5). This would make the `GitRepository` instances available to all Step instances. This will be repetitive. 

Can you please elaborate on what you mean with "passing it to the main functions"?

**Comment by kevgo** [comment]
This is blocking on #1421

**Comment by charlierudolph** [comment]
I was referring to the functions in the Step interface.

**Comment by kevgo** [comment]
Sorry, I'm still not sure what you have in mind here but want to implement this. I don't see a `main` function in the [step interface](https://github.com/git-town/git-town/blob/master/src/steps/step.go#L5-L12). Can you please point me to an example?

**Comment by kevgo** [comment]
I think you mean to change the step interface to:

```go
type Step interface {
	CreateAbortStep() Step
	CreateContinueStep() Step
	CreateUndoStep() Step
	GetAutomaticAbortErrorMessage() string
	Run(repo *git.Repo) error
	ShouldAutomaticallyAbortOnError() bool
}
```

That would be a very elegant solution!

**Comment by charlierudolph** [comment]
May need to pass the repo into the `Create*Step` as well but yeah that was what I was thinking

**Comment by kevgo** [comment]
This is now implemented.
