### ISSUE TITLE
Should there be a `git town config` option to enable safe deletion of branches?

### ISSUE THREAD

**Issue by cirego** [git-town/git-town#1393]
`git town` calls `git branch -D` under the hood to kill branches whether or not they have been fully merged into another branch. I'm not sure of the full rationale for why this is the case, but I can imagine that much of it has to do with how branches are being merged into each other. So, even though a branch may not have a difference between itself and its parent, `git branch -d` will still fail due to the differing merge commits.

Once `git town diff-parent` is added, it would be great to consider making `git town kill` 
(either by configuration or by default) verify that there are no differences between the two branches. There are probably some edge cases I haven't considered here, in addition of course to the extra testing required for a new flag.

**Comment by kevgo** [comment]
Hi @cirego, the use case for `git town kill` is to get rid of a branch that one doesn't intend to ship. An example is when I do an experiment in a feature branch, and the experiment doesn't turn out as expected, then I just want to delete this branch and try something else in a new feature branch.

Branches that have "good" changes that should be shipped will get deleted using the other Git Town commands. `git town ship` will remove the shipped branch. If a branch was shipped somehow differently, for example via the GitHub UI, then `git town prune-branches` will remove it (assuming one deletes the remote branch via the GitHub UI as well). If there is a use case to delete "empty" branches (branches that have no difference to the main branch), that could be added to the `git town prune-branches` command as well. Such cleanups should be done in bulk, which is what `git town prune-branches` does.

This is why `git town kill` has such a strong name. It is intended to "kill" a single branch that is still "alive", i.e. has actual changes, but which we don't need anymore.

**Comment by kevgo** [comment]
I am closing this issue because I think I was addressed in the comments. Please reopen if there are further ideas, questions or comments around this topic!
