### ISSUE TITLE
Add pre commit checks

### ISSUE THREAD

**Issue by blaggacao** [git-town/git-town#1501]
That ought to speed up (my) careless committing cycles and free (my) brain space for the other things.

**Comment by kevgo** [comment]
What exactly do you want to add to these pre-checks?

**Comment by kevgo** [comment]
I have a concern and an idea  :)

The concern is that Prettier is unfortunately pretty slow (thanks to being written in Node). I think it's important that commits remain really fast, ideally instantaneous. I am already annoyed that `git push` takes a couple of seconds and often don't don't push for that reason. I commit a lot while developing, each time I have something working. If I have to wait a number of seconds for Prettier to run, only to have the commit possibly fail after that, it's going to not be fun.

The good news is that there is an even better way! All the things in `make fix` (gofmt, Prettier) can be run when saving files in your editor. It's super easy with the respective Go and Prettier plugins:

- [run Prettier on file save in Vim](https://github.com/prettier/vim-prettier)
- [run gofmt on file save in Vim](https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L831-L833)
- [run Prettier on file save in VSCode](https://github.com/prettier/prettier-vscode)
- [run gofmt on file save in VSCode](https://code.visualstudio.com/docs/languages/go#_formatting)

If you use another editor, I don't know but am sure it is possible to get done. This is the best way in my opinion. You see properly formatted code while coding. Not just after committing. What do you think?

**Comment by blaggacao** [comment]
That feedback loop would have even a smaller footprint, but unfortunately, it's a little less scalable across environments.

In another project, I use https://www.npmjs.com/package/pretty-quick which works instantly and does automatically stage the result (sic!), pretty neat. I could quickly prepare a branch for you to test. Even if in the end, it's not merged... :D

**Comment by blaggacao** [comment]
Think about it, you might be right. Better shorten the feedback loop as much as possible.

**Comment by kevgo** [comment]
Yeah, pretty-quick would be the way to go in a pre-commit hook. But a you say, reducing the time code is unformatted is the best approach here. I agree that this isn't particularly portable. Here is what I do to make my setup portable: https://github.com/kevgo/dot-files. All I have to do is create a symlink to `.config` in my root directory (plus a [few more steps](https://github.com/kevgo/dot-files/blob/master/guides/chromeos.md)) and I have my entire environment configured. This allows me to re-install a machine in 30 min.
