### ISSUE TITLE
Uncached error

### ISSUE THREAD

**Issue by blaggacao** [git-town/git-town#1527]
Uncached error:
```zsh
➜  ~git-town git:(master) make build
go install -ldflags "-X github.com/git-town/git-town/src/cmd.version=v0.0.0-test -X github.com/git-town/git-town/src/cmd.buildDate=today"


➜  ~git-town git:(master) which git-town
/home/blaggacao/go/bin/git-town


➜  ~git-town git:(master) git sync

[master] git fetch --prune --tags

[master] git rebase origin/master
Successfully rebased and updated refs/heads/master.

[master] git push --tags
Everything up-to-date


➜  ~git-town git:(master) 1
~/ghq/github.com/coredns/ldap


➜  ldap git:(master) git sync
2020/06/04 12:44:45 Unknown step type: *FetchUpstreamStep


➜  ldap git:(master) git town config

Main branch:
  master

Perennial branches:
  [none]

Branch Ancestry:
  master

Pull branch strategy:
  rebase

New Branch Push Flag:
  false

```

Not sure what causes this, this error should be more useful ...

**Comment by kevgo** [comment]
This happens in [json_step.go](https://github.com/git-town/git-town/blob/5c475fc888862158300bdaecb2935caedbe11828/src/steps/json_step.go#L107). Apparently you are running into an edge case for which we have no feature spec. What does the command `1` do on your machine?

**Comment by blaggacao** [comment]
It just changes to the 1-previous directory...

**Comment by kevgo** [comment]
Does the error happen if you don't run `1` between the two runs of `git sync`? I.e. when you run `git sync` twice?

**Comment by blaggacao** [comment]
Yes the error produces idem-potently on all `git sync` in this repo.

```zsh
➜  ldap git:(master) ✗ git remote -v
origin    git@github.com:xoe-labs/coredns-ldap.git (fetch)
origin  git@github.com:xoe-labs/coredns-ldap.git (push)
upstream        https://github.com/coredns/example.git (fetch)
upstream        https://github.com/coredns/example.git (push)
```

**Comment by charlierudolph** [comment]
Running git-town in two different directories should not effect each other. We save the previous run state based in a temp file built from the current directory. https://github.com/git-town/git-town/blob/master/src/steps/run_state_to_disk.go#L59

I think this means in the `ldap` folder you had a failed git-sync previously. I've seen this a few times but pretty rare and still not certain on how to reproduce. Can discard the state (`git town discard`).

**Comment by blaggacao** [comment]
@charlierudolph yep that worked. Let's see if we can get to the root, though...

```shell
➜  ~ldap git:(master) git town discard && git town sync

[master] git fetch --prune --tags

[master] git rebase origin/master
Successfully rebased and updated refs/heads/master.

[master] git fetch upstream master
From https://github.com/coredns/example
 * branch            master     -> FETCH_HEAD

[master] git rebase upstream/master
Successfully rebased and updated refs/heads/master.

[master] git push --tags
Everything up-to-date
```

**Comment by kevgo** [comment]
Or add the `FetchUpstreamStep` to [jsonStep](https://github.com/git-town/git-town/blob/5c475fc888862158300bdaecb2935caedbe11828/src/steps/json_step.go#L107)? But only if there is a legit use case for it that we can reproduce in a feature test.
