### ISSUE TITLE
"git town compress" command

### ISSUE THREAD

**Issue by kevgo** [git-town/git-town#1529]
When developing a contribution for a project that merges or rebases commits
I want to be able to squash all commits in my feature branch into one
So that my submission occurs as a single commit in the Git history.

```cucumber
Scenario: squashing multiple commits on a feature branch
  Given my repo has a feature branch named "existing-feature"
  And the following commits exist in my repo
      | BRANCH  | LOCATION        | MESSAGE     | FILE NAME | FILE CONTENT |
      | main    | local, remote   | main_commit | main1     | main content |
      | feature | local, remote   | feature_1   | file1     | content 1    |
      |         |                 | feature_2   | file2     | content 2    |
      |         |                 | feature_3   | file3     | content 3    |
  When I run "git town compress"
  Then my repo now has the following commits
      | BRANCH  | LOCATION        | MESSAGE     |
      | main    | local, remote   | main_commit |
      | feature | local, remote   | feature_1   |
  And my repo now has the following committed files
      | BRANCH  | NAME  | CONTENT      |
      | main    | main1 | main content |
      | feature | file1 | content 1    |
      |         | file2 | content 2    |
      |         | file3 | content 3    |
```

### implementation

For each branch:
- `git reset <parent branch_>`
- `git commit`
- `git push --force-with-lease --force-if-include`
- if the push fails:
  - pull updates
  - push again

Commit message:
- By default it follows the behavior of `git rebase -i` and asks the user for the commit message. The pre-populated commit message is all the existing commit messages concatenated. The format is documented at https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History:

  ```
  # This is a combination of 3 commits.
  # This is commit message #1:
  
  one
  
  # This is commit message #2:
  
  two
  
  # This is commit message #3:
  
  three
  ```
- If the user runs `git town compress --no-edit`, it uses the pre-populated commit message without asking the user.

**Comment by blaggacao** [comment]
Yes, please allow to craft not only a single one, but also a series of well crafted commits!!! - I appreciate commit message story telling for review.

Sometimes the consolidated thought process is relevant to the general history, especially if non-normal choices are made.

**Comment by kevgo** [comment]
Your use case is covered by #1383. This ticket is for the opposite use case: people like me who do things in many small steps, with some detours and lots of polish and cleanup at the end. Also, many open-source projects expect contributions as a single squashed commit. It would be nice to simply run `git compress` in such a case.

Speaking of which, this should pull updates from remote, then squash all the commits together, then do a force-push.

**Comment by kevgo** [comment]
Use `git push --force-with-lease` to avoid losing changes.
