### ISSUE TITLE
Fix Autocompletion for Fish

### ISSUE THREAD

**Issue by blaggacao** [git-town/git-town#1531]
There is a pending upstream issue for the new autocompeltion implementation for fish shells.

Tracking upstream bug: https://github.com/spf13/cobra/pull/1122

Once merged + released, fix the workaround / cautionary note in the docs.

**Comment by sgarfinkel** [comment]
@blaggacao That issue is closed. Is this just a matter of updating the dependency version in the repo?

**Comment by blaggacao** [comment]
@sgarfinkel As far as I can remember: yes + the respective [docs update](https://github.com/git-town/git-town/commit/fbe905374377a78bdf4529333ba662e10a7ede14#diff-2951498f48a1a6b7709b210b2a989e1cdefafbc187dc27136594d8ff595493daR33-R34). Please feel free to give it a try.
