### ISSUE TITLE
Custom port

### ISSUE THREAD

**Issue by blaggacao** [git-town/git-town#1535]
`git town new-pull-request`

with

`git remote -v`
`ssh://git@gitea.playground.xoe.cloud:222/....git`

generates the following URL, which in any case is wrong...

`https://gitea.playground.xoe.cloud/222/.../compare/nma-cleanup-pre-commit...test`

**Comment by kevgo** [comment]
Indeed, I don't think Git Town supports custom ports yet.

**Comment by kevgo** [comment]
I wouldn't call that a bug, though, more a missing feature.

**Comment by blaggacao** [comment]
There is even more to this one: this is just the ssh protocol port, it wouldn't affect the actual hostname at all, so I guess I sjould just change the hostname.

Maybe the most sensible thing for git-town to do would be to drop all ports and resort to `80` & `443`, respectively.

If hosting is done on a different port, then it's definitively need-to-configure.

Alternatively, we could check the schema and adopt the port only if it's `http` or `https`. What do you think? Is it worth improving at all?

**Comment by kevgo** [comment]
Do you have a specific use case from the real world? I have personally never encountered a Git server with a different port. There is so much tooling around Git that would break in such a situation. Examples are GUIs for Git (like [GitKraken](https://www.gitkraken.com)), IDE plugins, command-line tools etc.

Btw there is already a config setting to customize the Git server address: [git-town.code-hosting-origin-hostname](https://github.com/git-town/git-town/blob/master/documentation/commands/new-pull-request.md). Does this solve your problem?

**Comment by blaggacao** [comment]
> Btw there is already a config setting to customize the Git server address: git-town.code-hosting-origin-hostname. Does this solve your problem?

Indeed, this solves my problem. Actually thats what I was trying to say in my previous post. :smile:
