### ISSUE TITLE
Git Town set-parent-branch fails after running 'git checkout -b'

### ISSUE THREAD

**Issue by cirego** [git-town/git-town#1636]
I made a local commit to `main` that I wanted to move to another branch so that I could code review the change. I created another branch and tried to set the parent branch to `main`. However, when I tried that, git-town exits because it cannot unset the config for `foo`, presumably because I created `foo` using `git checkout -b` and not `git town hack`.

```
]] git checkout main
]] git checkout -b foo
]] git town --debug set-parent-branch
git town --debug set-parent-branch
DEBUG (1): git rev-parse
DEBUG (2): git status
DEBUG (3): git rev-parse --abbrev-ref HEAD
DEBUG (4): git config --unset git-town-branch.foo.parent

Error: exit status 5
```

**Comment by cirego** [comment]
Running `git town sync` works as expected, but I *really* didn't want to run that because it makes reverting the original commit on `main` much harder.

**Comment by cirego** [comment]
Turns out running `git town sync` actually pushed this change to `origin`. Luckily this was a trivial change, but this could have been worse.

**Comment by kevgo** [comment]
`git town hack` would also sync the main branch with it's remote, i.e. push the unwanted commit to `origin`. The correct solution in your situation would be to undo the problem asap, i.e. undo the wrong commit to main:

- `git checkout main`
- `git reset HEAD^`  (the last commit is gone, changes from it are still there but uncommitted)
- `git checkout foo`
- commit on the foo branch
- `git town sync` or `git town new-pull-request` (will ask for the parent branch of `foo`)

I don't see anything that Git Town should do differently here. @cirego what do you think?

**Comment by cirego** [comment]
@kevgo your solution definitely works for the use case that I ran into (undo a commit on local main and move to another branch). However, from a user perspective, `git town set-parent-branch` should still work if I create a branch manually.

**Comment by kevgo** [comment]
Agreed, good point. Thanks for the bug report! From the debug info you sent (thanks for that as well), it seems like it tries to delete the existing parent branch information (`git config --unset git-town-branch.foo.parent`), which fails because it doesn't exist, causing the entire command to fail.

The best way to go about this would be to execute https://github.com/git-town/git-town/blob/master/src/cmd/set_parent_branch.go#L27 only when this parent branch information exists.

**Comment by kevgo** [comment]
This works now! 🎉
