### ISSUE TITLE
Issues continuing git-town sync

### ISSUE THREAD

**Issue by charlierudolph** [git-town/git-town#1637]
Ran into issues lately where after a sync hit a merge conflict, if I run `git town continue` after resolving conflicts but not committing, it doesn't push the branch (looks like its auto-aborting but I'm not sure).

Committing and then running `git town continue` works as expected. 

I'll try to get more details the next time this happens

**Comment by kevgo** [comment]
I run into the same issue, happens intermittently.

**Comment by kevgo** [comment]
Possible cause: running `git-town` from a subdirectory in the repo

**Comment by charlierudolph** [comment]
Believe this is caused by git-town being in a subdirectory of the repo.

The method we use to check if a merge is in progress depends on being at the root level of the repo: 

https://github.com/git-town/git-town/blob/cfe8ddbb006286dcc12faf027aa0fea71712efbb/src/git/runner.go#L609

Should be able to reproduce this with a test. Expect for resolution we need to prepend a step to continue / abort step lists to move to the root of the repo

**Comment by charlierudolph** [comment]
Discovered our tests are insufficient as this test for example runs the initial command from a subdirectory but the continue / abort commands do not run from the sub-directory:

https://github.com/git-town/git-town/blob/v7.4.0/features/sync/folder_does_not_exist_on_main_branch/conflict.feature

**Comment by charlierudolph** [comment]
Fixed in https://github.com/git-town/git-town/commit/a5b86870ca325627d1d8e57c3857e0ffe8a2e348
