### ISSUE TITLE
Allow using tool for commits

### ISSUE THREAD

**Issue by blaggacao** [git-town/git-town#1641]
I have figured the best approach to keep the mainline git history conforming to any particular schema, when working with non-expert (git) command line users, is to use a tool like `cz` (commtizen) to construe the git massage interactively.

Hence it would be useful to allow defining a cmd from the environment as a tool to construe the `git town ship` message (either merge or squash).

I consider that for regular `git town sync` this is not warranted.

&rarr; Opening an editor for reviewing the final commit message is fine nevertheless with the added benefit of seeing all the squashed commits (if that's possible) and reformulate where necessary.

---

A visual of such tool:
![image](https://user-images.githubusercontent.com/7548295/96177260-2e350300-0ef3-11eb-8e32-a7b2995fe4d4.png)

**Comment by kevgo** [comment]
Have you tried setting `cz` as the default editor for Git? 

```
git config --global core.editor cz
```

See https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration for more details.
