### ISSUE TITLE
Git Town support for GitHub Auto Merge

### ISSUE THREAD

**Issue by cirego** [git-town/git-town#1658]
GitHub now has support for [automatically merging a PR](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request). This feature is really useful when the status checks take a non-trivial amount of time (5+ minutes). It's a productivity killer to try and use `git town ship` in this situation because I'm often forced to suspend the `git town ship` command until the status checks pass.

Unfortunately, `git town` doesn't know how to treat PRs that have been auto-merged (with squash merge, to be precise) and will default to reopening the branch. The "best" workaround that I have come up with is to run `git town kill` on the branch after it has been merged.

Alternately, if there were a method for disabling `git town sync` when doing a `git town ship` where I have enabled merge via GitHub, that would also workaround the problem. This would mean that I can run `git town ship` without needing to wait for status checks to rerun.

**Comment by kevgo** [comment]
You can run `git town prune-branches` to remove branches whose remote has been shipped via other means, for example using GitHub. Related issue: https://github.com/git-town/git-town/issues/1209

**Comment by cirego** [comment]
Thanks for the quick response! I'll try this out. I'm curious to see how `prune-branches` works with child branches.

**Comment by kevgo** [comment]
This should work with child branches. See the [end-to-end test](https://github.com/git-town/git-town/blob/master/features/prune-branches/nested_branches.feature) and the [code](https://github.com/git-town/git-town/blob/cfe8ddbb006286dcc12faf027aa0fea71712efbb/src/cmd/prune_branches.go#L76-L82). Please let us know if you run into any issues!

**Comment by cirego** [comment]
I can confirm that this works as I expected once I started using `prune-branches`. Thanks Kevgo!
