### ISSUE TITLE
git town prune-branches error

### ISSUE THREAD

**Issue by vnguyen972** [git-town/git-town#1664]
Hi, this happens to me a lot recently

Error: cannot determine if branch "Fix_Me" has unmerged commits: exit status 128

The branch has no unmerged commits and the branch has no upstream branch anymore.. that's why I want to prune it but unable to with 'git town prune-branches'

Any idea?

**Comment by kevgo** [comment]
Interesting. Pruning branches is pretty stable functionality that hasn't changed in years. To help us investigate this, please provide the output of the following commands:

1. `git --version`
2. `git-town version`
3. the complete output of the `git-town prune-branches` command that fails.

Thanks!  🙂

**Comment by vnguyen972** [comment]
Below is the capture of my terminal. Agreed, I used it last year (couldn't remember the version bc I have left that position) but it was very stable, never failed.. I'm not sure maybe something else is causing it (the way Git was setup? idk)

Thanks.

```
$ git --version
git version 2.30.1

$ git-town version
Git Town v7.5.0 (2021-03-11T05:01:50Z)


$ git-town prune-branches

[adding_back_uri_header] git fetch --prune --tags

Error: cannot determine if branch "welcome_email_modification" has unmerged commits: exit status 128

To abort, run "git-town abort".
To continue after having resolved conflicts, run "git-town continue".
```

**Comment by charlierudolph** [comment]
I've generally experienced some issues when using git-town within vscode where I hit an exit code 128 where it outputs the errors message `Unable to create <Path to git repo>/.git/index.lock: File exists`. I think we should update the error message to output the command run and stdout / stderr from running the command to give us more information

**Comment by kevgo** [comment]
This Git command seems to fail: `git log master..welcome_email_modification`, see https://github.com/git-town/git-town/blob/master/src/git/runner.go#L79. Agree that we need to add better diagnostics when encountering such errors. Ideally Git Town prints something that people can copy-and-paste into a bug report.

**Comment by vnguyen972** [comment]
Thanks very much.

Though, it turns out that when I did:
git-town config 

..it shows me that I have set the main-branch to something that have been removed a while back.

so by resetting that configuration; it started working for me!

Lesson learned, always checking your configuration :)

Thank you.  
This issue could be closed.
