### ISSUE TITLE
Windows Defender AV is alerting on v7.5 installed with scoop as being 'Zpevdo' malware

### ISSUE THREAD

**Issue by rohancragg** [git-town/git-town#1665]
Threat name: Trojan:Win32/Zpevdo.B
path: %USERPROFILE%\scoop\apps\git-town\7.5.0\git-town.exe
SHA: 058b733479bb67412703bb697fecb424b5e752a5

Also 17 other security vendors are flagging it as malicious:
https://www.virustotal.com/gui/file/713f7a4332fba878068077c44bfc9f027776eba3146265addb826d064acc9b73/detection

**Comment by kevgo** [comment]
Thanks for letting us know!

**Comment by kevgo** [comment]
Have you ruled out a malware infection on your machine that spread to git-town.exe?

**Comment by kevgo** [comment]
Executables written in Go are often falsely flagged as malicious by virus scanning programs. See https://go.dev/doc/faq#virus for more background. More discussion also at https://www.reddit.com/r/golang/comments/s1bh01/goexecutables_and_windows_defender.
