### ISSUE TITLE
Importing Packages 

### ISSUE THREAD

**Issue by sheldonhull** [git-town/git-town#1669]
Been simplifying some workflow for my team and I'm a big fan of git town. There are some workflow steps I'm considering and thought of importing git town as a package to invoke some of the workflow directly as part of this. Wondering if this makes sense over calling the binary directly and if you have seen anyone else use it like that.

Example: 

- I'd invoke new pr
- run most of the commands git town hack does, request a work number, in my code pull the work item title and dynamically set the branching and PR links. 
- run standard linter/security check
- sync

Yes I can chain together task commands to do this but figured I'd examine calling the command directly if it made sense instead of relying on the binary directly.

This is just a casual inquiry not a feature request as I think through it. 

Thanks again!

**Comment by kevgo** [comment]
Hey Sheldon, you should be able to manually assemble a list of Git Town steps that you want to execute. Just look at how Git Town commands are implemented. For example, let's take a look at how `git town new-pull-request` works internally:

- the `Run` method is called by the CLI framework (in our case https://github.com/spf13/cobra) with the CLI args: https://github.com/git-town/git-town/blob/master/src/cmd/new_pull_request.go#L36-L54
- this method determines all the relevant information (branch to create PR for, its parent branches, etc): https://github.com/git-town/git-town/blob/master/src/cmd/new_pull_request.go#L37
- it loads a driver to talk to the code hosting service (e.g. the GitHub): https://github.com/git-town/git-town/blob/master/src/cmd/new_pull_request.go#L41
- it determines the individual steps to execute into a `stepList`: https://github.com/git-town/git-town/blob/master/src/cmd/new_pull_request.go#L45
- it executes the `stepList`: https://github.com/git-town/git-town/blob/master/src/cmd/new_pull_request.go#L49

You should be able to run these steps from any Go codebase. The interesting part is compiling the step list: https://github.com/git-town/git-town/blob/master/src/cmd/new_pull_request.go#L93-L107

- for each branch in the ancestry line of the branch to create a PR for, add the steps to sync that branch: https://github.com/git-town/git-town/blob/master/src/cmd/new_pull_request.go#L94-L99
- wrap this step list in steps to stash open changes away at the beginning and pop those stashed changes back at the end: https://github.com/git-town/git-town/blob/master/src/cmd/new_pull_request.go#L101
- after all this is done, add the step that opens the browser with the PR URL: https://github.com/git-town/git-town/blob/master/src/cmd/new_pull_request.go#L105


A caveat though: The internal structure of Git Town is not covered by any stability guarantees like semantic versioning and might change at any time (and has done so several times in the past) without notice. By now Git Town is pretty mature and stable, so larger changes should not really happen anymore.

**Comment by sheldonhull** [comment]
@kevgo  thank you so much for such a detailed answer. If I decide to do this I'll keep in mind this content and caveat. Super helpful! Thanks again!

**Comment by kevgo** [comment]
Closing since this ticket isn't actionable right now.
