### ISSUE TITLE
feat(new-pull-request): command flag to disable browser window

### ISSUE THREAD

**Issue by ericis** [git-town/git-town#1679]
If there was a flag to disable the automatic browser window, would this command be the same as `git-town sync`?

**Comment by kevgo** [comment]
Currently there is no flag to disable the automatic browser window when running `new-pull-request`. The command doesn't create a pull request. The users are supposed to do that in the browser window that is opened for them. 

Can you outline your case that makes you want to not show the browser window?

**Comment by ericis** [comment]
Yes, `make` is calling `git-town new-pull-request` in a containerized dev environment, so I want the output logged, but no browser. (i.e. the developer is instructed to take manual steps on their host browser).

I noticed `git-town sync` pushes the branch, so I am wondering if I just need to generate the PR URL or if `new-pull-request` does anything else?

**Comment by kevgo** [comment]
Yes, `git-town new-pull-request` does nothing more than what `git-town sync` does and then it prints the URL to open the browser.

**Comment by kevgo** [comment]
You could solve your use case by running `git-town sync` and then printing the URL for the pull request yourself.

**Comment by ericis** [comment]
Awesome. Closing this for my use case with the option to run `git-town sync` and then echoing a PR URL.
