### ISSUE TITLE
Wrong git ship commit author even I select another

### ISSUE THREAD

**Issue by alphatroya** [git-town/git-town#1681]
I select the author of PR in the selection prompt during the `git ship` command but this selection is dropped and commit created by my authorship. I suspect git configuration for this project: I have overridden email in the local `.git/config` file (The name is not changed).

Maybe this is correct behavior, and local configuration precedes selection, can you clarify this point? 

Git Town v7.6.0 (2021/11/24)

**Comment by kevgo** [comment]
The current behavior is documented (and tested) [here](https://github.com/git-town/git-town/blob/main/features/ship/current_branch/on_coworker_feature_branch.feature). It does run `git commit -m "feature done" --author "coworker <coworker@example.com>"` in this scenario, see [this line](https://github.com/git-town/git-town/blob/main/features/ship/current_branch/on_coworker_feature_branch.feature#L28).

One way to investigate your use case is running this with the `--debug` switch enabled (i.e. `git ship --debug`). This will tell you whether Git Town runs  the correct or wrong Git command.

**Comment by alphatroya** [comment]
<img width="1027" alt="Снимок экрана 2022-01-13 в 11 28 57" src="https://user-images.githubusercontent.com/4927633/149294169-f12118b4-61b3-4f59-aed0-0c2ae61efd22.png">

Well, it's strange, looks like git town uses local environment and ignore any selection. I think there's a mistake, why is this prompt even here?

**Comment by charlierudolph** [comment]
Believe I found the bug here:

https://github.com/git-town/git-town/blob/8ed329fda7817aa1e83d1d8970cf2dd68eb14488/src/steps/squash_merge_branch_step.go#L55-L61

It appears we only use the author if a commit message is also supplied via the CLI. Otherwise the author is not used. I'll work on a fix for this

**Comment by alphatroya** [comment]
Can confirm it, now `ship` command works correctly. Thanks for your work and great tool!
