### ISSUE TITLE
sync pops an extra stash if there are no changes but a modified submodule

### ISSUE THREAD

**Issue by avh4** [git-town/git-town#1741]
# Steps to reproduce
- have a repo with a submodule
- be on a feature branch that is currently up-to-date with the main branch
- have at least one manually created stash
- make a change in the submodule
- run `git town sync`

# Current outcome
- The modified submodule makes git-town think that there are changes that need to be stashed, but when it runs `git stash`, no stash is created because "No local changes to save" (git stash ignores submodules)
- after merging and pushing, git-town thinks the stash needs to be popped, but running `git stash pop` pops a previously-saved stash because the stash git-town thought it created wasn't actually created

# Expected outcome
I'd expect `git town sync` not to try to pop one of my real stashes.  Beyond that, I guess I'd just expect the submodule to be ignored.
Maybe the quickest fix would be to filter out submodules when git-town is checking if there are changes that need to be stashed.

**Comment by avh4** [comment]
> Maybe the quickest fix would be to filter out submodules when git-town is checking if there are changes that need to be stashed.

It looks like that could probably be achieved by adding `--ignore-submodules` to `Runner.HasOpenChanges` https://github.com/git-town/git-town/blob/7ecf85669af1e06918003713c67b614f44b17433/src/git/runner.go#L601

**Comment by kevgo** [comment]
Thanks for the thoughtful bug report! The fix you propose works really well. #1744 reproduces and fixes the extra stash pop in "git sync". If you encounter other issues with submodules, please report them as well.

**Comment by kevgo** [comment]
Git Town 7.7.0 fixes this issue.
