### ISSUE TITLE
uncommitted changes should be breaking changes to existing commits

### ISSUE THREAD

**Issue by kevgo** [git-town/git-town#176]
This is an important edge case that our specs should cover. 

This code might be needed here.

``` ruby
# Executes the given block with the uncommitted changes stashed away
def without_open_changes
  do_stash = has_uncommitted_files
  stash_open_changes if do_stash
  yield
  restore_open_changes if do_stash
end
```

**Comment by kevgo** [comment]
I think this case is a superset of `with open changes` and should replace it. I'm hesitant to add 50% more tests to our test suite. We are already pretty severely over-tested.

**Comment by charlierudolph** [comment]
@kevgo are updated thoughts on this? This requires too much setup to me as we may need to create additional just commits to ensure that the checkout will fail due to conflicts unless we stash.

This was brought up before we verified what commands were run and I think that is good enough.

**Comment by kevgo** [comment]
I still think this is an edge case that can happen quite frequently. Pretty much anytime there are uncommitted changes that conflict with something on the main branch. So I still feel (relatively strongly) that we should test this in some form. 

All we should need here is a commit on main. Most of our specs already have that. 

I'm happy to keep the main spec for a feature simple and on the happy path, and adding a dedicated spec that just verifies that the command works with these types of breaking changes.

**Comment by kevgo** [comment]
We have these spec now.
