### ISSUE TITLE
git-town does not construct correct url for self-hosted GitLab with non-standard SSH port.

### ISSUE THREAD

**Issue by vectro** [git-town/git-town#1891]
Suppose you have a remote like
`origin  ssh://git@gitlab.domain:1234/group/project`

Expected Behavior: git-town will construct URLs like
`https://gitlab.domain/group/project/merge_requests`

Actual Behavior: git-town constructs URLs like
`https://gitlab.domain/1234/group/project/merge_requests`

**Comment by kevgo** [comment]
Just to make sure I understand you correctly: For your setup, you want Git Town to create this URL: 
`https://gitlab.domain/1234/group/project/merge_requests`? Shouldn't it be
`https://gitlab.domain:1234/group/project/merge_requests`?

**Comment by vectro** [comment]
I suppose we can't know for sure what port is available for HTTPS, but I think it is almost certainly not the port used for SSH.

**Comment by kevgo** [comment]
This works now.
