### ISSUE TITLE
`git-town version` doesn't work on debian

### ISSUE THREAD

**Issue by leos** [git-town/git-town#1893]
Repro:
1. install git-town 7.8.0 on debian bullseye: `curl -L "https://github.com/git-town/git-town/releases/download/v7.8.0/git-town_7.8.0_linux_intel_64.deb" -o "git-town.deb" && dpkg -i git-town.deb`
2. run `git-town version`

Expected: `Git Town v7.8.0 (2022/08/07)` (works properly on macos)
Actual: `Git Town  ()`

**Comment by kevgo** [comment]
Thanks for letting us know! #1929 should fix this.
