### ISSUE TITLE
`git-town sync --no-verify`

### ISSUE THREAD

**Issue by ericis** [git-town/git-town#1927]
Would love to be able to run something like `git-town sync --no-verify` (or the alias `git sync --no-verify`).

With the expectation of git-town running the command `git push --no-verify`.

This would intentionally skip git hooks (e.g. Husky pre-commit) the same as running `git push --no-verify` without git-town would act.

Use case:
We have a large mono-repository with a LOT of pre-commit checks. Simply switching from a feature branch to main and running sync results in a TON of tasks that are not required with zero changes to push. This makes git-town pretty unusable for `sync`. e.g. `git checkout main && git sync` (where `git push` results in a Husky pre-commit hook script that runs lots of linting and testing tasks b/c `push` was called)

Similar, but not at all the same: #1680

**Comment by kevgo** [comment]
I assume when working on your monorepo, you would probably want to use `--no-verify` all the time. So maybe this should be a [preference](https://www.git-town.com/preferences.html). This would also have the nice side effect that it applies to all the other commands that make pushes, like `hack`, `rename-branch`, and `ship`.

**Comment by kevgo** [comment]
Possible name for the preference: `git-town.push-verify` with valid settings `true` and `false`.
