### ISSUE TITLE
support remotely shipped nested branches

### ISSUE THREAD

**Issue by kevgo** [git-town/git-town#2037]
I have nested feature branches:

```
main
 \
  feature1
   \
    feature2
```

Git Town knows the branch hierarchy.

I submit a PR for `feature1`, the maintainer merges my MR and deletes the branch on the remote.

On the next sync, Git Town should update `feature2` to have the parent `main`.

**Comment by ruudk** [comment]
This would also allow the PR author to merge its own PR on the GitHub interface, without having to use `ship`.

**Comment by kevgo** [comment]
This should work in the upcoming v10 release: https://github.com/git-town/git-town/blob/main/features/sync/current_branch/feature_branch/tracking_branch_deleted/features/multiple_ancestors_shipped.feature
