### ISSUE TITLE
v7.9.0 is pointing to the wrong commit

### ISSUE THREAD

**Issue by benmoss** [git-town/git-town#2048]
https://github.com/git-town/git-town/commits/v7.9.0 points to bab5e6837322cde5b3f93aa7418a11c4f21049b6

it seems like the intention was to have it point to 7250e3a2bdf8295c69596b002c8ac8cef942a5ed

xref https://github.com/Homebrew/homebrew-core/issues/122686

**Comment by kevgo** [comment]
Thanks for the shrewd observation and taking the time to reach out! :pray: Normally you would be 100% correct. In this particular situation, however, the tags are correct. Background: All the changes in v7.9 were made in December 2022. That release just got delayed a few weeks. The commits after https://github.com/git-town/git-town/commit/bab5e6837322cde5b3f93aa7418a11c4f21049b6 contain breaking changes, which will be releases as v8.0.

**Comment by kevgo** [comment]
@benmoss The website shows the docs for `main`. The `main` branch currently contains a number of larger unreleased changes (which will become v8.0 soon). Hence the website varies quite substantially from the latest released version. 

I hope to release v8.0 no later than next week, which will get the website in sync with the released product again. This should be the last set of larger changes to Git Town. 

Is there a particular issue that breaks Homebrew right now that I can help fix?
