### ISSUE TITLE
Unexpected Escape Sequence: ['\x1b' 'O'] 

### ISSUE THREAD

**Issue by koppor** [git-town/git-town#2194]
I am running git-town in WSL2. I connect to GitTown using [ConEmu](https://conemu.github.io/). When pressing "cursor down" at the prompt of "Please specify the main development branch:", I get following error:

    Error: cannot read branch from CLI: Unexpected Escape Sequence: ['\x1b' 'O']

This seems to be a similar issue as https://github.com/cli/cli/issues/3071, but I have no clue why it happens in this year.

**Comment by kevgo** [comment]
https://github.com/go-survey/survey/issues/341#issuecomment-903982101 says:

> PowerShell 7.2.0-preview.8 no longer exhibits this issue

If you are using PowerShell, can you please verify that you run the latest version?

**Comment by koppor** [comment]
> If you are using PowerShell, can you please verify that you run the latest version?

Sorry that my words "I am running git-town in WSL2. I connect to GitTown using [ConEmu](https://conemu.github.io/)." were not understandable, so here a screenshot:

![image](https://user-images.githubusercontent.com/1366654/230139330-78a20660-3ff8-40d9-af61-ba57e85649e8.png)

```terminal
$ git-town version
Git Town  ()
```

I installed it using following command:

```
sudo dpkg -i git-town_7.9.0_linux_intel_64.deb
```

```terminal
$ sha512sum < /usr/bin/git-town
56baaef2f21441d021202dacdbf0024fe4ff15a1c184379e3faa56e5ebad55b6f72f905434315b78240648ca656a94466d16b88ded7c8b6c3a881d9a94ba6a24  -
```

**Comment by kevgo** [comment]
Thanks for clarifying. The [new Windows terminal](https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701) allows connecting to all sorts of shells (Command Prompt, PowerShell, WSL). I'm not sure whether ConEmu works the same way.

In general, Git Town still uses Survey v1 because Survey v2 introduces performance regressions. It is possible that an update to v2 might fix this problem. If you feel curious to try this out:

- install Go 1.19 or 1.20
- clone https://github.com/git-town/git-town onto your machine
- check out the [kg-survey-v2 branch](https://github.com/git-town/git-town/tree/kg-survey-v2)
- run `make build`
- run `~/go/bin/git-town` and see if it fixes the error

Thanks!

**Comment by koppor** [comment]
Thank you for the quick reaction! Needed to run `make update` (and install yarn and NodeJS 14 to make that work), too 😅.

Think, I am not good enough for go compilation...

```cmd
echo Please update the third-party tooling in the Makefile manually.
Please update the third-party tooling in the Makefile manually.
 koppor  ~/git-repositories/git-town   kg-survey-v2 ●  make build
go install -ldflags "-X github.com/git-town/git-town/v7/src/cmd.version=7.9.0-156-g3e149594-dev -X github.com/git-town/git-town/v7/src/cmd.buildDate=2023-04-06"
# github.com/git-town/git-town/v7/src/hosting
src/hosting/gitea.go:20:27: assignment mismatch: 2 variables but c.client.ListRepoPullRequests returns 3 values
src/hosting/gitea.go:68:11: assignment mismatch: 2 variables but c.client.MergePullRequest returns 3 values
src/hosting/gitea.go:76:22: assignment mismatch: 2 variables but c.client.GetPullRequest returns 3 values
make: *** [Makefile:17: build] Error 1
```

Meanwhile, I found a work around - re-configuring ConEmu to use following command to open WSL2:

```bat
set "PATH=%ConEmuBaseDirShort%\wsl;%PATH%" & %ConEmuBaseDirShort%\conemu-cyg-64.exe --wsl -cur_console:pm:/mnt
```

Source: https://conemu.github.io/en/CygwinMsysConnector.html#wslbridge

**Comment by koppor** [comment]
The output changed to "Unzulässige Funktion"

``´
koppor@DESKTOP-KAK953S MINGW64 /c/git-repositories/koppor/heylogs (develop)
$ git-town hack add-jbang-hint

[develop] git fetch --prune --tags
Git Town needs to be configured

? Please specify the main development branch:  [Use arrows to move, enter to select, type to filter]
> remotes/upstream/dependabot/github_actions/develop/actions/checkout-4
  develop
  remotes/upstream/HEAD
  remotes/upstream/develop
  remotes/upstream/dependabot/maven/develop/org.checkerframework-checker-qual-3.38.0
  remotes/upstream/master

Error: cannot read branch from CLI: Unzulässige Funktion.
```

Git Town 9.0.1 (2023-07-29)

**Comment by kevgo** [comment]
Git Town v10 has been released with a ton of changes. Can you please see if the issue still exists in that version?
