### ISSUE TITLE
git sync --stack

### ISSUE THREAD

**Issue by kevgo** [git-town/git-town#2202]
### functionality

- updates only the current branch stack: all feature branches that are ancestors or descendents of the current branch
- `git compress --stack` already has similar behavior, all the code and logic is there

### benefits

- faster than `git sync --all` (in large monorepos)
- reduces pressure on CI

**Comment by WhosNickDoglio** [comment]
> updates only the current branch stack: all feature branches that are ancestors or descendents of the current branch

This _sounds_ like this covers my use case but just wanted to double check I'm reading this right before I go and create a new issue! 

I find myself coming back and updating branch after some PR review in the middle of the stack and would like after I address the comments and run `git sync` the **full** stack be updated with my changes and not just the branches up to the one I just modified. 

For a more concrete example lets say I have a stack of three branches (A -> B -> C) with A pointing towards main. If I get feedback on B after I address it and run `git sync` I'd like the whole stack to be updated **including C**.  I hope that makes sense 😅

**Comment by kevgo** [comment]
Hi @WhosNickDoglio you can already do what you want to do (syncing the _entire_ stack after updating one branch in it) by running `git sync --all`.

This ticket merely proposes a more lightweight version of `git sync --all`. Let's say you have your stack, still with branches A->B->C. You also have an unrelated branch X that also points towards main. When you run `git sync --all`, it syncs branches A, B, C, and X. When you run `git sync --stack`, it syncs only A, B, and C.

**Comment by WhosNickDoglio** [comment]
Okay so this is **exactly** what I'm looking for! 

`git sync --all` is a little heavy handed since I have many local branches (many of which may not be related to the current stack I"m working in) so I'll be **exciting** waiting for `git sync --stack` 🎉

**Comment by kevgo** [comment]
Great to hear that you would find this feature useful! In the meantime, you could experiment with [parking](https://www.git-town.com/advanced-syncing#parked-branches) the other branches, or limit syncing them in other ways described in the linked website.
