### ISSUE TITLE
option to not push new commits on the main branch

### ISSUE THREAD

**Issue by kevgo** [git-town/git-town#2224]
Extracted from https://github.com/git-town/git-town/issues/2223#issuecomment-1518338374:

When the `protected-main-branch` option is set, 
https://github.com/git-town/git-town/blob/5ef3afa47c2c0d6a898bcd525ad11f4d69b3136d/features/sync/current_branch/feature_branch/rebase_sync_strategy/sync_current_feature_branch_using_rebase.feature#L20 should not happen. Instead, if it finds an unpushed commit on `main`, it should print an error notifying the user that there is an unpushed commit on `main`.

**Comment by ruudk** [comment]
Would this be something for V10 as well 🙏 ?

**Comment by kevgo** [comment]
This ticket is more about adding documentation for an edge case that people might run into if they don't follow their development workflow. I don't consider it critical so it is rather low on the list right now.

**Comment by kevgo** [comment]
Closing this ticket in favor of #4104, which contains a better idea on how to implement this using a new sync strategy. Let's continue the conversation there. Thanks for the input on this ticket!
