### ISSUE TITLE
`git-town switch` in VSCode terminal has off-by-one key presses 

### ISSUE THREAD

**Issue by brandonaut** [git-town/git-town#2261]
Not sure if this is a VSCode issue or a git-town issue.

In the VSCode integrated terminal, navigating branches with `git-town switch` is off-by-one with my key presses. That is, the terminal highlights the previous branch that was selected. This is very consistent -- as long as I keep track in my head how many times I pressed the down arrow, I can use `git-town switch` just fine. This reproduces with both pwsh and cmd.

In Windows terminal (not in VSCode), `git-town switch` does not have this key-press delay. Tested with both pwsh and cmd.

I haven't seen this behavior with any other TUIs in the VSCode terminal.

Environment:
- Windows 11
- VSCode 1.79.2
- git-town 9.0

Thanks for creating git-town, BTW. It is truly a marvelous tool.

**Comment by kevgo** [comment]
Thanks for reporting this. I can't reproduce this in VSCode on macOS but will try on Windows once I'm back from traveling. 

> Thanks for creating git-town, BTW. It is truly a marvelous tool.

Thanks for saying this. It really means a lot! 🙏 💚

**Comment by brandonaut** [comment]
Also, I don't see the off-by-one issue for other interactive menus in git-town, such as `git-town hack -p`

**Comment by kevgo** [comment]
I can reproduce this behavior in the Git Bash on Windows (the one that uses the old terminal engine). Also in VSCode. This might be caused by the fact that the "git town switch" command uses a different library to read keyboard events: https://github.com/eiannone/keyboard. I'll try a few other ways of reading the keyboard events that don't exhibit this broken behavior.

**Comment by kevgo** [comment]
This issue should be resolved when rewriting the dialog UI using https://github.com/charmbracelet/bubbletea as part of v12.
