### ISSUE TITLE
[Feature Request] Allow to configure a different MergeMethod for ship cmd, to support Github new feature Merge Queue

### ISSUE THREAD

**Issue by mribichich** [git-town/git-town#2324]
Github shipped a new feature called Merge Queue.

Which uses `merge` as the `MergeMethod`.

So please allow to configure a different **MergeMethod** for `ship` cmd.

https://github.blog/2023-07-12-github-merge-queue-is-generally-available/
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request-with-a-merge-queue?tool=cli
https://docs.github.com/en/free-pro-team@latest/rest/pulls/pulls?apiVersion=2022-11-28#merge-a-pull-request

```
        result, _, err := c.client.PullRequests.Merge(context.Background(), c.Organization, c.Repository, number, body, &github.PullRequestOptions{
                MergeMethod: "squash",
                CommitTitle: title,
```

**Comment by kevgo** [comment]
The merge queue is super exciting and Git Town already fully supports it! On the branch that you want to ship:

1. Run `git new-pull-request` - this opens the GitHub UI to create a new pull request in your browser.
2. Fill out the fields, optionally tag reviewers, click the `Merge when ready` button. Please note that you can still choose all three ways of merging (merge, rebase, or squash) with the merge queue, see [the docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#managing-a-merge-queue).
3. When the merge queue ships the branch for you, it deletes it on GitHub's side. Once that has happened, you can run `git prune-branches` to delete the shipped branch from your local Git repo.

When using the merge queue, you won't use the `git ship` command at all.

**Comment by mribichich** [comment]
ok. I thanks for that.
I understand.
Anyways, It would be nice for this to be transparent. cos just by allowing a different merge method, I dont have to go to the UI whenever I think it's ready, and then run the prune cmd.

I know about docs for the merge methods, but it seems that in order to close the PR using the API, it requires `merge` as the method

ok, so it would be a suggestion then.

thanks again!

**Comment by mribichich** [comment]
The thing about using `prune` cmd is that it would delete even the ones you want to keep.
that's why I dont use it.
sometimes you want to keep a branch locally or whatever

**Comment by kevgo** [comment]
> it seems that in order to close the PR using the API, it requires merge as the method

To my knowledge GitHub doesn't **require** the `merge` method anywhere. You **can** use it when merging PRs manually via the GitHub UI or via the merge queue.

Git Town's `git ship` command currently always squash-merges branches because that's the right thing for the vast majority of users. One of Git Town's paradigms is to make Git easier to use correctly. Another paradigm is "when in doubt keep it out" to keep Git Town simple and easy to learn. When somebody comes up with a convincing use case for another merge method for shipping, we will add it. Just saying "GitHub also supports it" is a valid data point but by itself not convincing enough in this context.

> The thing about using prune cmd is that it would delete even the ones you want to keep.

Can you outline a scenario where keeping a shipped branch around in your local repo is desired? The shipped branch in your local repo will contain no changes after you have shipped it because the changes it contains are now also on your main development branch. You can always still see the commits and the changes that the now shipped branch contains through GitHub's UI.

**Comment by mribichich** [comment]
As far as I know, when using a merge queue, you can't no longer use squash as the merge method in the PR.
Cos now that would be handle by the queue. Which you configure the way to merge from their configuration . It doesn't matter what was your PR method anymore.

I do agree doing squash, but specifying that in the Par using a merge queue, it's not possible. The only option available from the PR becomes merge.
Then the merge queue will use whatever method it had configured.

My thinking was making all of this transparent.

I wasn't trying to change doing merge commit instead of squash.

Maybe adding a config for GH, called like using merge queue, that would allow the tool to know how to target the merge method differently.

About the prune CMD, maybe I have a wrong understanding about it. I wasn't talking about shipped branches, no branches without remotes. Maybe POCs. I could have pushed that to remote or not.
But they haven't shipped.
So if the CMD checks for remote branch existence, it might think that it has shipped.

Anyways, I understand about keeping it simple, but it kinda sucks, from using one CMD to ship, to having to go to the UI, and then run another CMD that does other stuff, not just to my branch. 
It has a sort of side effect since it also prunes other branches.

Maybe a way to tell the ship CMD to ship using merge queue or something.
