### ISSUE TITLE
Was v9.0.1 retagged?

### ISSUE THREAD

**Issue by p-linnane** [git-town/git-town#2363]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. We noticed that the shasum for v9.0.1 of git-town has changed. We wanted to verify this is legitimate before updating it in our repository. Thanks!

Relates to https://github.com/Homebrew/homebrew-core/pull/139423

**Comment by kevgo** [comment]
Hi @p-linnane 👋 yes I have re-tagged that commit. If that's a problem on your end, I can change my deployment workflow to be more careful to avoid re-tagging in the future. Please advise. Thanks!

**Comment by p-linnane** [comment]
No problem. We grab the shasum when the release is made, so if it changes afterward our workflows throw an error for security reasons. I appreciate the info and I'll get it updated on our side. Thanks!
