### ISSUE TITLE
git delete: remove the content of the killed branch from its descendents

### ISSUE THREAD

**Issue by kevgo** [git-town/git-town#2388]
Assuming I have this branch hierarchy:

```
branch-1
 \
  branch-2
   \
    branch-3
```

I decided that `branch-1` was a bad idea and I want to remove it. If I run `git town kill branch-1`, it removes branch-1 from the lineage. But branch-2 and branch-3 still contain the changes that branch-1 makes, and shipping branch-2 will also ship the changes from branch-1.

To fix this, `git town kill` should also revert the changes from branch-1 from the other branches.

Maybe only do this if a switch like `--revert` is provided.

**Comment by nishchay-manwani-glean** [comment]
Up until this is added, what would be the easiest workaround right now?
Currently I do 
1. `git town switch` to branch-1
2. `git compress`
3. `git revert` on the commit hash generated
4. `git sync --all`
5. `git kill`

I was wondering if there is any easier way which anyone might be using?

**Comment by kevgo** [comment]
merged this into #3338

**Comment by kevgo** [comment]
@nishchay-manwani-glean Thanks for sharing how you do this! 🙏

**Comment by kevgo** [comment]
The `git town delete` command now properly removes commits of the deleted branch from descendent branches.
