### ISSUE TITLE
push all branches and tags at the end of a Git Town operation

### ISSUE THREAD

**Issue by kevgo** [git-town/git-town#2581]
`git push --all origin`

**Comment by defunctzombie** [comment]
My preference as a user is to avoid pushing tags at the end of an operation. I've actually found myself searching for how to disable the behavior of `git push --tags` at the end of a `git town sync` operation.

I see in this comment: https://github.com/git-town/git-town/issues/2906#issuecomment-1876034893 you have the following reasoning:

> If you don't add any tags locally, running this command does nothing, so no problem.

> If you intentionally add a new tag locally, it's better to try to push it to the server. Git tags are meant to be shared. Keeping your local Git workspace in sync with the rest of the world is Git Town's job.

My experience does not align with that same assumption. _Because_ the upstream repo is a shared resource, what is pushed does influence what others see and the tags available. I can understand how tags are thought of similar to branches and if you share an upstream with branches, why not tags? I think for me that reasoning breaks down a bit when you think of `git town` as a branching workflow automation tool. Because my focus when using `git town` is around branches, I view the capturing and pushing of tags as bystanders to that workflow. I expect `git town` to work with my branches and not tags.

**Comment by kevgo** [comment]
@defunctzombie thanks for sharing your perspective! Can you please describe the specific reason why you don't want to share Git tags that exist on your local machine with the other developers?

**Comment by defunctzombie** [comment]
@kevgo from my perspective framing it as "don't want to share Git tags" is maybe attributing a different workflow than what I am expecting. When I use `git town` to work on feature branches my mental model is that I am working with branches. Tags are some other aspect of git and not the thing I am trying to think about with how it might or might not interface with the upstream repo(s). Maybe some folks have a workflow where ensuring tags are pushed is important; but that is not our team. I'd probably also be surprised if I thought it was a default folks wanted vs could opt-into if it was important for their workflow.

**Comment by kevgo** [comment]
Thanks for the extra info! I still don't understand why you want Git Town to not sync tags.

> Tags are some other aspect of git and not the thing I am trying to think about with how it might or might not interface with the upstream repo(s). Maybe some folks have a workflow where ensuring tags are pushed is important; but that is not our team. 

It sounds like you don't care about Git tags at all and don't use them in your development workflow. If I understood that correctly, why does it "bother" you that Git Town syncs tags? Why not simply ignore the tags that Git Town syncs?

Tags are typically used to label code releases. This can be useful in development when triangulating bugs reported by users. Here is an example:
- A user of Git Town reports a problem with Git Town. They use Git Town version 11.1.0.
- I cannot reproduce the bug on the `main` branch. This could mean the bug was fixed in the meantime, or that I don't know how to reproduce it.
- I check out the version of the code base that release 11.1.0 had: `git checkout v11.1.0`
- I can reproduce the bug on that version. Now I know how to reproduce it, and can verify that it is correctly fixed on the `main` branch.

Syncing of tags was added after Git Town users requested it. There hasn't been much discussion about Git tag support in the last couple of years. Most people seem to be okay with it.

In any case, it sounds like you want to support https://github.com/git-town/git-town/issues/3212. That's great to know and bumps the priority of that ticket!

**Comment by defunctzombie** [comment]
> Tags are typically used to label code releases

I agree - which is why I would not want any random cruft from my machine making its way to the central repo. Maybe what I really want to say is that I don't want to _implicitly_ push my tags in `git town` operations but I would not mind pulling the _official tags_ from upstream.

**Comment by kevgo** [comment]
Thanks for sharing your perspective on tags. I see your point. I now agree that a feature that makes tag syncing optional makes sense.

**Comment by kevgo** [comment]
Concerns about this approach:

1. Git Town cannot run `git push --all` because that would break observed branches. We have to curate a list of branches to push.

2. Git Town cannot push all pushable branches to origin in a single operation because different branch types might require different ways of pushing: `sync-feature-strategy` vs `sync-perennial-strategy` vs `sync-prototype-strategy`. So we would need to store two lists of branches to push in the runstate.

3. This approach increases the time between pull and force-push for ALL branches, even if only one branch has merge conflicts. We want to force-push each branch as quickly as we can to minimize the likelihood of additional commits at the tracking branch.

4. Pushing a lot of branches at the same time might cause other problems like overloading the remote server or CI systems. Some teams, for example on a large monorepo that experiences scalability issues, might discourage the practice.

5. All of the reasons above indicate a need for a config flag for going back to pushing each branch individually if needed. So we would have to maintain two separate implementations for pushing branches.

6. There isn't any user need for this. It's just an idea because it's possible.

Building this is doable and there might be performance gains in situations like `git sync --all`. But this feels like premature optimization and YAGNI. The benefits might not be worth the cost here.
