### ISSUE TITLE
limit pulling the main branch

### ISSUE THREAD

**Issue by heyitsaamir** [git-town/git-town#2657]
First of all, this probably shouldn't be a github issue, but I'm not sure where else to ask this! I'm just getting started with git town so this might be a basic question --

I work in a big repo with lots of contributors. I created a new branch and `set-parent` to an existing branch. I'd have liked to just have rebased on top of that branch without pulling the latest master (when master gets pulled, i need to do a full `yarn` to download packages etc). Is this possible to do with `sync`?

**Comment by kevgo** [comment]
Hey Amir, that's a great question and an interesting use case! Here are two ideas that might get you want you want in your situation. I'm using your terminology, i.e. "new branch" for the branch that you created, and "existing branch" for the branch that is the parent of "new branch".

You could make the "existing branch" a [perennial branch](https://www.git-town.com/preferences/perennial-branch-names). Perennial branches are long-lived standalone branches like `master`, `production`, `development`, `staging`, etc. What separates them from feature branches is that they don't receive updates from the main branch.

```
git town config perennial-branches update
```

In the dialog that shows up when you run this command, enable the checkbox next to the "existing branch" name. Now you can run `git sync` and it does what you want: it pulls updates from the remote of the "existing branch", but it doesn't update `master` and it doesn't pull `master` into "existing branch" and "new branch". You can create pull requests for your "new branch" and ship it into this "existing" (and now perennial) branch as usual. To create pull requests or ship the "existing branch", you have to remove it from the perennial branches.

Another idea is to put Git Town into offline mode. In offline mode, Git Town doesn't pull any updates from the network. It just syncs the branches in your local workspace with each other. In this scenario you would have to run `git pull` or `git pull --rebase` manually on the branches you want to fetch updates for. Then any `git sync` should be safe in the sense that it doesn't pull any additional updates from the network.

```bash
git town config offline on
```

**Comment by heyitsaamir** [comment]
Thank you! I had actually tried the offline mode, but it doesn't seem to be working for me. It's actually doing the fetch and pull. I'm not sure if I'm doing something wrong 🤔

**Comment by heyitsaamir** [comment]
For your reference -- notice how it rebases on top of origin/master.

![image](https://github.com/git-town/git-town/assets/48929123/cdf4ee05-b5f4-4732-8237-cebf0367a0c3)

Hmm, it's not doing a fetch, but I think my vscode periodically does a fetch, so maybe that combo is broken

**Comment by heyitsaamir** [comment]
FWIW, the perennial-branches is a great workaround. I'll probably write up a script so that this is easy to set up and sync when I need to

**Comment by kevgo** [comment]
Some background on how Git works might help understand what's going on here. Due to the nature of Git as a distributed version control system, your local clone contains the _entire_ repo content including all commits and all branches from the server. `origin/master` is the local copy of the `master` branch that exists at the `origin` server. 

Git operations like `merge` and `rebase` happen on local copies of branches. `git rebase origin/master` updates your local `master` branch with commits in the local copy of the `master` branch from `origin`. 

Then you periodically download updates from the server to your local client (`git fetch`) and upload updates made on your local client to the server (`git push`). `git pull --rebase` is a convenience command that runs `git fetch` and `git rebase origin/<branch>` under the hood.

The way offline mode works right now is that it simply doesn't fetch. It still syncs what your local repo is aware of, including local copies of remote branches. This does what it should do as long as you never fetch manually.

If you or VSCode runs `git fetch` periodically under the hood, then your local Git repo contains unsynced updates of the remote branches, and Git Town syncs them even if offline mode is enabled. Because offline mode is enabled, it doesn't push them up to the server.

You can verify whether you have successfully enabled offline mode by running `git town config offline`.

**Comment by kevgo** [comment]
FYI there have been a number of reports requesting this feature. I'm collecting them and ideas how to address your use case better in https://github.com/git-town/git-town/issues/2711.

**Comment by heyitsaamir** [comment]
> @heyitsaamir assuming Git Town has a feature that allows you to avoid pulling in updates from the master branch. Would you enable this behavior for all your feature branches, or just for a few that you manually select?

I'd probably enable it by default. I'm used to graphite's model where they only pull things if you explicitly run a `sync` command. I generally prefer this because:
1. It works better for me for larger codebases (faster)
2. Less cognitive overhead that i'm in offline mode or not
3. I work while travelling (airplanes etc), so sometimes my access to wifi is slow. This is when i can get a lot of focused work done, so I'd rather not kick off a git pull if i can help it.

**Comment by kevgo** [comment]
Thanks this is helpful, and graphite looks cool! Follow-up question to help me fully understand what you have in mind here.

> I'm used to graphite's model where they only pull things if you explicitly run a sync command.

How is this different from Git Town? Git Town also only pulls things if you run a `sync` command.

> [when my internet is slow during traveling] I'd rather not kick off a git pull if i can help it

Simply don't run `git pull` or `git sync` then? Do you mean that you would want to sync only the local branches when traveling, and only pull updates over the network when running the explicit "sync" command?

I'm sure I'm missing something here. Can you please describe in more detail which exact Git operations you would like to be run (roughly) in each of the scenarios you describe (office with fast internet, traveling with slow internet)? How would an ideal Git Town tool behave in your use case? Thanks! 🙏

**Comment by kevgo** [comment]
[New features](https://www.git-town.com/advanced-syncing) added in v12.1 improve the developer experience around this:

- make the existing branch a [contributing branch](https://www.git-town.com/commands/contribute)
- now when you run `git sync` it does what OP suggests: it updates `new branch` only with commits made to `existing branch` and not with commits added to `master`

**Comment by kevgo** [comment]
Additional request for this in https://github.com/git-town/git-town/issues/2673#issuecomment-1829983692

**Comment by kevgo** [comment]
Possible idea to implement this: #2171

**Comment by kevgo** [comment]
The simplest step towards providing this functionality is adding a flag to `git sync` that prevents pulling in the main branch. Something like `git sync --skip-main`. These manual overrides are needed anyways, even in the presence of a more systematic solution like #2171.

**Comment by kevgo** [comment]
To make this work for stacks based on perennial branches other than main, it's probably better to call this something like `--skip-root` or `--headless`.

**Comment by kevgo** [comment]
`--detachef`

**Comment by kevgo** [comment]
It should be possible to combine the `--detached` flag with flags like `--all`, `--stack`, and `--no-push`.

**Comment by kevgo** [comment]
@heyitsaamir thanks for submitting this really useful feature request. Starting with [v16.1](https://github.com/git-town/git-town/releases/tag/v16.1.0) you can run `git sync --detached` to prevent pulling the main branch. Enjoy!
