### ISSUE TITLE
Specify glob pattern for perennial branches

### ISSUE THREAD

**Issue by tranhl** [git-town/git-town#2659]
# Feature Request

It would be nice to be able to specify glob patterns for perennial branches instead of discrete branch names (e.g. `release-*` instead of `release-v1.0 release-v1.1 ...`) so that branches that match the pattern are automatically treated as perennial branches.

# Motivations

Branching for release is pretty common practice, with release branches being cut from `main/master` for each new release. When making hotfixes for releases, it's pretty common to branch from the affected release branch to make the hotfix. Running `git town sync` without setting the release branch as perennial will prompt Git Town to sync the main branch onto the release branch, which would cause a whole bunch of issues. However, it's quite cumbersome to have to add each release branch as perennial, and it could also lead to human error.

**Comment by kevgo** [comment]
That's a great idea!

**Comment by kevgo** [comment]
To implement this, all that is needed is adjusting the [GitTown.PerennialBranches](https://github.com/git-town/git-town/blob/b4811743d1c7d899a59a97b5afaf461ce8079f0d/src/config/git_town.go#L189-L196) method. If one of the configured perennial branch names looks like a regex, make it also return all branch names that match this regex.

**Comment by tranhl** [comment]
@kevgo Is there any chance this could make it into v11? It would be amazing to not only have a shared Git Town config, but also be able to declare globbed perennial branches in this config to share with the team as well. It would be the missing piece for team-wide adoption for us!

**Comment by kevgo** [comment]
@tranhl I am currently working on better team support for Git Town: [shared config file](https://github.com/git-town/git-town/issues/2748) and [syncing branch lineage through pull requests](https://github.com/git-town/git-town/issues/2745). Your ticket fits into this overall topic and I hope to get to it when the two tickets mentioned above are done.

**Comment by kevgo** [comment]
Btw great to hear that you consider Git Town for your team! I'd love to hear any other feedback around this (good or bad).

**Comment by tranhl** [comment]
> I'd love to hear any other feedback around this (good or bad).
Absolutely, I'm pretty keen on introducing the Git Town workflow into the team! Will definitely have feedback what works/doesn't once globbed perennials are released.

**Comment by kevgo** [comment]
Quick update on this: this is planned for one of the next Git Town releases. In the meantime, you could list your release branches in the new configuration file (). With this in place, you can update the config when there is a new release, and the Git Town installations of your team members gets updated automatically the next time they run `git sync` or `git hack`.

**Comment by tranhl** [comment]
This is great news! We've already updated Git Town to v12 on our team, and the shared configuration file is a godsend for keeping everyone's setup in sync.

As you've suggested, we've just listed out all the possible perennial branches ahead of time as a workaround. Once this ships we can then update it to a single glob:

```toml
[branches]
main = "main"
perennials = [
  "release-v3.0",
  "release-v3.1",

  "release-v4.0-rev.1",
  "release-v4.0-rev.2",
  "release-v4.0-rev.3",
  "release-v4.0-rev.4",
  "release-v4.0-rev.5",

  "release-v4.1-rev.1",
  "release-v4.1-rev.2",
  "release-v4.1-rev.3",
  "release-v4.1-rev.4",
  "release-v4.1-rev.5",
]
```

**Comment by kevgo** [comment]
I really like the idea of listing the future perennial branches in the config file. This way these branches will automatically be perennial for everybody the moment they are created!
