### ISSUE TITLE
argument and filtering on switch command

### ISSUE THREAD

**Issue by JCB-K** [git-town/git-town#2708]
- would be nice to be able to write `git-town switch branch-name`
- alternatively filter-as-you-type, fzf style.

I'm happy to implement this myself, but I'd need some guidance.

**Comment by kevgo** [comment]
> would be nice to be able to write git-town switch branch-name

How would this be different from running [git checkout branch-name](https://git-scm.com/docs/git-checkout) or the new [git switch branch-name](https://git-scm.com/docs/git-switch)?

> alternatively filter-as-you-type, fzf style

I like this idea a lot! One concern is that it would conflict with the current modal (VIM based) motion commands. A possible approach is to enable the fzf functionality only after pressing the `/` key. There could be a config setting for whether to start in VIM mode or in FZF mode.

Implementing this is pretty straightforward. The implementation of the current dialog is at https://github.com/git-town/git-town/blob/main/src/cli/dialog/modal_select.go. In that file, the `print` method displays the dialog and the `handleInput` method handles input.

**Comment by JCB-K** [comment]
> How would this be different from running [git checkout branch-name](https://git-scm.com/docs/git-checkout) or the new [git switch branch-name](https://git-scm.com/docs/git-switch)?

I don't know, I got into the habit of using `git-town switch` mostly because it shows me my options :). I guess I also assumed it did something special, but now I realise it doesn't. I'll probably go back to using a shell function that combines fzf and git checkout:

```bash
fbr () {
	local branches branch
	branches=$(git branch --sort=-committerdate)  && branch=$(echo "$branches" | fzf-tmux -h 15 +m)  && git checkout $(echo "$branch" | sed "s/.* //")
}
```
