### ISSUE TITLE
git sync: option to not push

### ISSUE THREAD

**Issue by teumas** [git-town/git-town#2715]
Sometimes when hacking away on a feature branch I would like to perform **git sync** in order to fetch changes from the remote, but without pushing my changes to the remote.

Something like **git sync --no-push**, which performs all the steps of sync but stops short of pushing my local changes to the remote branch.

This would be great when I need to verify that my code and the changes from upstream work together correctly before I push my changes.

**Comment by kevgo** [comment]
related: #1680

**Comment by kevgo** [comment]
This now works! `git sync --no-push` does not push local branches.

**Comment by kevgo** [comment]
A dedicated config setting for disabling all pushes is now available as part of [Git Town 22](https://github.com/git-town/git-town/releases/tag/v22.0.0).
