### ISSUE TITLE
sync on the main branch fails when pushing tag

### ISSUE THREAD

**Issue by alokpr** [git-town/git-town#2906]
Trying git-town for the first time, so I might be missing something.

Is there an option to disable pushing tags on the main branch because we disable "push" on the protected branches. I am getting the following error when git-town attempts to push an existing tag:

```
$ git town sync --all

[main] git fetch --prune --tags
From gitlab.com:dexrobo/core
 ! [rejected]            v230322.0.3 -> v230322.0.3  (would clobber existing tag)

Error: exit status 1
```

**Comment by kevgo** [comment]
Hi @alokpr a setting to disable pulling and pushing tags does not exist yet but would be trivial to add. 

FYI in the Git Town output you shared, Git Town _pulls_ (not pushes) Git tags from the remote server onto your machine. Your local workspace already has tag `v230322.0.3` but it points to a different commit and hence aborts. This seems unusual.

Can you please describe your setup and use case in more detail?

**Comment by alokpr** [comment]
You are absolutely correct - it was failing during fetch. I force updated local tags and now all commands work as expected. Thanks!

**Comment by alokpr** [comment]
I noticed that as a final step, tags are being pushed on the main branch (which is protected): `[main] git push --tags`

It does not fail since everything is already up to date, but is it expected to push to origin on the main/perennial branch?

**Comment by kevgo** [comment]
Yes, Git Town intentionally pushes tags when syncing the main or a perennial branch. This works well even if some branches are protected. Here is the thinking behind this:

If you don't add any tags locally, running this command does nothing, so no problem.

If you intentionally add a new tag locally, it's better to try to push it to the server. Git tags are meant to be shared. Keeping your local Git workspace in sync with the rest of the world is Git Town's job. 

If your company doesn't allow pushing locally created tags, and somebody accidentally creates a tag locally, it is still better to try to push it to the server and fail. This way, Git Town helps this developer realize their mistake and fix it by deleting the local tag.

Does this make sense to you?

**Comment by alokpr** [comment]
Yes, your logic makes sense to me - thanks for the detailed explanation.
