### ISSUE TITLE
`scoop update` doesn't see new versions

### ISSUE THREAD

**Issue by brandonaut** [git-town/git-town#2983]
`scoop update git-town` still shows 10.0.2 as the latest version. I think this is because the naming of the git-town assets changed starting in 10.0.3, with the version number no longer being included. Here's the Scoop auto updater string: https://github.com/ScoopInstaller/Main/blob/e03fc1937f04b5d9486cc83f73d61a77b7239406/bucket/git-town.json#L22

Was this change in naming intentional? If so, then the Scoop bucket needs to be updated. Otherwise, I guess the naming of the release artifacts needs to be fixed.

**Comment by kevgo** [comment]
The fix got merged. `scoop update git-town` now correctly installs v11.1.0 on my machine. Thanks again for reporting this! 🙏
