### ISSUE TITLE
git town config setup does not remember code-hosting-platform

### ISSUE THREAD

**Issue by bryanlarsen** [git-town/git-town#3043]
How to reproduce:

- installed by typing `go build` in the repo (2dce25589dec1870d4a8cb116595d51abe957475) and copying the binary to /usr/local/bin
- go to a repo cloned off a self-hosted gitlab
- type `git town config setup`.
- at hosting prompt, select gitlab
- at where to save prompt, choose to save prefs file in repo
- hack a bit
- `git propose`
- get error "Git Town needs to be configured" although it already has been.   Grumble and do it again
- get error "Error: unsupported hosting platform"
- `git propose`
- get error "Error: unsupported hosting platform"

to fix it I had to `git config git-town.code-hosting-platform gitlab`

**Comment by kevgo** [comment]
Thanks for filing this and sorry for the problem. The setup assistant is still under active development (especially the part with the hosting platform) and not officially released. Did you save the configuration as a config file or as Git metadata?

**Comment by kevgo** [comment]
Nevermind, I see that you store the config as a config file.

**Comment by kevgo** [comment]
Fixed in https://github.com/git-town/git-town/pull/3047. The hosting platform you configure in the setup assistant should show up in the config file now. And Git Town should use it. Thanks again for the timely bug report and please reach out if you encounter any other problems! 🙏
