### ISSUE TITLE
Set default config for new repositories

### ISSUE THREAD

**Issue by ruudk** [git-town/git-town#3151]
When I go into a new project that I haven't used Git Town with, I notice that it falls back to merge strategy, so it messes up my commits.

Is it possible to set a default config, to be used everywhere?

**Comment by kevgo** [comment]
Yes, that's possible. The most direct way to do this is to create a [global Git metadata entry](https://www.git-town.com/preferences/sync-feature-strategy#in-git-metadata):

```bash
git config --global git-town.sync-feature-strategy rebase
```

This makes `rebase` the default sync strategy for all repos on your machine. Individual repos can override this default.

Another approach is copying all config files you want to reuse from existing codebases into your new repos. Most people use a number of tools like code formatters, linters, Git Town, etc. All of them use config files. These config files are typically the same for each repo and can be copied between repos.

Finally, you could (as a best practice) always run the setup assistant in the new repo:

```
git town config setup
```

**Comment by ruudk** [comment]
Awesome, I completely missed the `[--global]` option. That solves it indeed!
