### ISSUE TITLE
support for sync-compatible amend-commit

### ISSUE THREAD

**Issue by kevgo** [git-town/git-town#3177]
### Problem

- Many developers work by amending existing commits. To commit changes, they run `git commit --amend` instead of `git commit`.
- This is incompatible with the current `git sync`. The commits on the local branch are now different from them commits on the tracking branch. When running `git pull --rebase`, Git mixes the new local commits with the old commits from the tracking branch. What we want instead is to keep only the local commits, and have them replace the commits on the tracking branch.
- see #2223 for more details

### Context

The solution is to do amend-commit locally and right after that force-push. This is typically done with a Bash script that looks something like this:

```bash
#!/usr/bin/env bash
set -e

git sync
git commit --amend
git push --force-with-lease
```

Git Town started as a collection of such Bash scripts, and was formalized into a tool so that people don't have to create such Bash scripts anymore. It would therefore be better if Git Town did what this Bash script does out of the box. 

### Solution

An additional Git Town command called `git town amend` that does this:

1. stash away the uncommitted changes
2. run `git pull --rebase`
   - now the local branch is up to date with the tracking branch and its safe to overwrite the tracking branch with the local commits in (5)
3. pop the stash
4. run `git commit --amend` with the arguments given to `git amend`
   - example: if the user ran `git amend --no-edit`, Git Town runs `git commit --amend --no-edit`
5. run `git push --force-with-lease`
   - this overwrites the commits on the tracking branch as requested above
   - this is safe because of (2)

On [stacked changes](https://www.git-town.com/stacked-changes):
- update the current branch and all its child branches first
- perform steps 4 and 5 from above to amend-commit and force-push the current branch
- on each child branch: `git rebase <parent>` and `git push --force-with-lease`

In short, developers would use `git town amend` or `git amend` instead of `git commit --amend` and Git Town would ensure that their changes get amend-committed in a way that `git sync` keeps working.

### challenges

- this triggers a full CI run for every commit
  - for the current branch and all its child branches
  - this is a lot of pressure on the CI server
  - there are other features that create CI pressure, e.g. #765
  - workarounds:
    - configure CI to not run on pushes for feature branches
    - add [ci skip](https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci) to commit messages, see #999 for details
- People have to remember to run `git amend`. This doesn't work if they commit any other way: using `git commit --amend`, using a visual Git tool, from within their IDE, etc.
- this juggles uncommitted changes around before they can be committed, leading to potential loss
  - this isn't as bad, they are persisted in the Git stash, which sticks around in case of conflicts during unstash
  - resolving the same conflicts during the rebase can also lead to data loss

**Comment by wederbrand** [comment]
This looks promising. 

For the use-case where the amend happens on the last commit on a (nested) branch it looks perfect.
For the use-case where each nested branch has a couple of commits and the amend (or an edit in interactive rebase) happens on any commit that isn't also the last one, I don't think it will work as good.

I've resorted to manually resetting and force pushing all my branch pointers after amending historic commits, always working from the top of my "final" branch. It's a little housekeeping but it saves me a lot of trouble.

**Comment by kevgo** [comment]
Thanks for the perspective!

> For the use-case where each nested branch has a couple of commits and the amend (or an edit in interactive rebase) happens on any commit that isn't also the last one, I don't think it will work as good.

Could you please describe the problem you expect when changing any existing commit except the last one? My hope is that force-pushing the new local commits to the tracking branch right after changing them locally should avoid most problems. But I don't do this much, so I might be missing something here.

> I've resorted to manually resetting and force pushing all my branch pointers after amending historic commits, always working from the top of my "final" branch. It's a little housekeeping but it saves me a lot of trouble.

It would be great to capture your expertise here so that others can benefit from them as well. Can you please provide which exact Git commands you run in this situation? 🙏

**Comment by wederbrand** [comment]
For that first use case your suggested step 4 only amends changes to the last commit. If I do an interactive rebase and amend to changes to any other commit, and then finish the rebase, there is nothing to stash and later amend. If git town does a git pull at that time it will change the local history.

I'll try to make an example of how I'm currently working soon.

**Comment by wederbrand** [comment]
This is a faked example of my current workflow. I typically have a couple of branches for easy reviewing and possibly part deliveriers. Like this (ignore the commit message, I'm using my advent of code repository to show case)
```
* 84e942b - (HEAD -> the_one_with_everything) 2019 12 (8 weeks ago) <Andreas Wederbrand>
* 19ab8c7 - (second_api) 2019 11 (8 weeks ago) <Andreas Wederbrand>
* 0b7402b - 2019 10 (8 weeks ago) <Andreas Wederbrand>
* c8b0d10 - 2019 09 (9 weeks ago) <Andreas Wederbrand>
* 3dba37d - 2019 08 (9 weeks ago) <Andreas Wederbrand>
* 2ea1b7d - (first_api) 2019 07 (9 weeks ago) <Andreas Wederbrand>
* bcdbc95 - 2019 06 (9 weeks ago) <Andreas Wederbrand>
* d7f7988 - 2019 05 (9 weeks ago) <Andreas Wederbrand>
* 7d5a04f - (database_changes) 2019 04 (9 weeks ago) <Andreas Wederbrand>
* c792937 - 2019 03 (9 weeks ago) <Andreas Wederbrand>
* 01f5099 - 2019 02 (9 weeks ago) <Andreas Wederbrand>
* 0696ce8 - (cleanup) 2019 01 (9 weeks ago) <Andreas Wederbrand>
* 846d7fc - 2023 25 (9 weeks ago) <Andreas Wederbrand>
```

Previously, if I needed to change the commit `01f5099 2019 02`, perhaps as a result of a review, I would check out "database_changes", do `git rebase -i` and stop at 01f5099, make the changes, amend and continue the rebase. 

Once done I need to force push and then rebase all the other branches onto it's parent and force push those.
git town can handle of these syncs but if I ever forget to force push I'm stuck with multiple commits, just as mentioned in #2223.

What I'm now doing instead is to stay in my the_one_with_everything branch, make change, do a fixup back to the commit that needed to change and have git rewrite all my commits, this makes all my other branches "dangling" and unchanged.

```
* 737e193 - (HEAD -> the_one_with_everything) 2019 12 (1 second ago) <Andreas Wederbrand>
* 52a955a - 2019 11 (1 second ago) <Andreas Wederbrand>
* 2f19045 - 2019 10 (1 second ago) <Andreas Wederbrand>
* c26ed9e - 2019 09 (1 second ago) <Andreas Wederbrand>
* e4617c4 - 2019 08 (1 second ago) <Andreas Wederbrand>
* 9395ce2 - 2019 07 (1 second ago) <Andreas Wederbrand>
* 612543f - 2019 06 (1 second ago) <Andreas Wederbrand>
* d879bb5 - 2019 05 (1 second ago) <Andreas Wederbrand>
* 428321f - 2019 04 (1 second ago) <Andreas Wederbrand>
* 82e3562 - 2019 03 (1 second ago) <Andreas Wederbrand>
* 92f1a20 - 2019 02 (5 seconds ago) <Andreas Wederbrand>
| * 19ab8c7 - (second_api) 2019 11 (8 weeks ago) <Andreas Wederbrand>
| * 0b7402b - 2019 10 (8 weeks ago) <Andreas Wederbrand>
| * c8b0d10 - 2019 09 (9 weeks ago) <Andreas Wederbrand>
| * 3dba37d - 2019 08 (9 weeks ago) <Andreas Wederbrand>
| * 2ea1b7d - (first_api) 2019 07 (9 weeks ago) <Andreas Wederbrand>
| * bcdbc95 - 2019 06 (9 weeks ago) <Andreas Wederbrand>
| * d7f7988 - 2019 05 (9 weeks ago) <Andreas Wederbrand>
| * 7d5a04f - (database_changes) 2019 04 (9 weeks ago) <Andreas Wederbrand>
| * c792937 - 2019 03 (9 weeks ago) <Andreas Wederbrand>
| * 01f5099 - 2019 02 (9 weeks ago) <Andreas Wederbrand>
|/
* 0696ce8 - (cleanup) 2019 01 (9 weeks ago) <Andreas Wederbrand>
* 846d7fc - 2023 25 (9 weeks ago) <Andreas Wederbrand>
```

But, the correct commit to point at can be found from looking at logs (I do this manually)
```

git branch -f database_changes 428321f
git branch -f first_api 9395ce2
git branch -f second_api 52a955a
```

making it all perfect again
```
* 737e193 - (HEAD -> the_one_with_everything) 2019 12 (5 minutes ago) <Andreas Wederbrand>
* 52a955a - (second_api) 2019 11 (5 minutes ago) <Andreas Wederbrand>
* 2f19045 - 2019 10 (5 minutes ago) <Andreas Wederbrand>
* c26ed9e - 2019 09 (5 minutes ago) <Andreas Wederbrand>
* e4617c4 - 2019 08 (5 minutes ago) <Andreas Wederbrand>
* 9395ce2 - (first_api) 2019 07 (5 minutes ago) <Andreas Wederbrand>
* 612543f - 2019 06 (5 minutes ago) <Andreas Wederbrand>
* d879bb5 - 2019 05 (5 minutes ago) <Andreas Wederbrand>
* 428321f - (database_changes) 2019 04 (5 minutes ago) <Andreas Wederbrand>
* 82e3562 - 2019 03 (5 minutes ago) <Andreas Wederbrand>
* 92f1a20 - 2019 02 (6 minutes ago) <Andreas Wederbrand>
* 0696ce8 - (cleanup) 2019 01 (9 weeks ago) <Andreas Wederbrand>
* 846d7fc - 2023 25 (9 weeks ago) <Andreas Wederbrand>
```

**Comment by wederbrand** [comment]
> The `git town amend` command we talk about in this ticket is only for use cases where people would use `git amend`. If you want to use `git rebase` instead, then you would have to use the [git town rebase](https://github.com/git-town/git-town/issues/3179) command.

I hadn't seen 3179, it makes perfect sense and is probably what I would use most out of these two new changes.

**Comment by kevgo** [comment]
Thanks for sharing your pretty sophisticated branch setup! You do a lot of branch management manually right now. I am pretty confident that we can make Git Town much more useful for your use case than it is right now.

Another idea in this context is https://github.com/git-town/git-town/issues/3182. This feature should allow rebasing any commits to your heart's content, and then `git sync` correctly pushes your local commits to the remote without clobbering your local commits with the outdated commits from the tracking branch. Assuming nobody else pushed commits to the tracking branch of course. Curious what you think!

**Comment by wederbrand** [comment]
#3182 looks good. All in all these changes supports a workflow where the local commits have a higher priority over remote commits. 

For me that's perfect, I very rarely collaborate on these changes. Perhaps for git-town it would be necessary to keep track of collaborative branches and personal branches, with a flag or a naming convention.

For personal branches the suggested changes makes sense, for collaborative branches perhaps the current functionally is most correct.

**Comment by kevgo** [comment]
This has been shipped in v13. Please try it out and reach out with any problems if you should encounter any!
