### ISSUE TITLE
On error, tell user to use `git town continue` instead of `git-town continue`

### ISSUE THREAD

**Issue by ruudk** [git-town/git-town#3208]
This might help new users. 

I interact with town using `git town`. Whenever there is a problem, town tells me to use `git-town` command. I think this is because that's the underlying binary of town itself.

It would be nice if it was smarter and knew I came from `git town` instead.

**Comment by kevgo** [comment]
Great idea! I agree that Git Town should be called as `git town` and not directly as `git-town`, and the documentation should reflect that.

**Comment by kevgo** [comment]
This is shipped in v13. Enjoy!
