### ISSUE TITLE
Add option to the configuration for not fetching/pushing tags during git sync

### ISSUE THREAD

**Issue by connected-rmcleod** [git-town/git-town#3212]
Tags are not an important part of my development workflow, which makes the tag fetching and pushing during `git sync` fairly unnecessary. It also causes problems in the repo I'm currently running in, since there are certain tags that are automatically updated by CI, so when git sync tries to fetch the tags I get the "would clobber existing tag" error, meaning that every time I git sync I have to run `git fetch --tags --force` first. The guidance on previous [issues](https://github.com/git-town/git-town/issues/1642) that have been raised about this is to use branches instead of tags if they're going to be moving, which I concede is probably correct, however the team that works out of this repo is very large and changes like this can be slow to make.

The possibility of having an option for disabling pulling tags was mentioned by @kevgo [here](https://github.com/git-town/git-town/issues/1642#issuecomment-713227706) and I think this would be quite useful to me if it's a change we might consider incorporating.

> None of this is specific to Git Town - you will run into the same challenges with vanilla Git or any other Git client. Having said all this, one way we could address this in Git Town is with a config option that disables pulling tags. Steps to implementing this:
> 
> 1. create a new configuration option `git-town.fetch-tags` (defaulting to `true`) similar to [shouldNewBranchPush](https://github.com/git-town/git-town/blob/master/src/config/config.go#L440-L453)
> 2. provide this config value to [Runner.fetch](https://github.com/git-town/git-town/blob/master/src/git/runner.go#L490-L497) and omit the `--tags` portion from the call to `r.Run` if the value is `true`
> 3. add integration tests with this feature disabled for at least one Git Town command, similar to https://github.com/git-town/git-town/blob/master/features/hack/new_branch_push_flag.feature
> 4. add this to the documentation of [git sync](https://github.com/git-town/git-town/blob/master/documentation/commands/sync.md), similar to how the documentation of [git hack](https://github.com/git-town/git-town/blob/master/documentation/commands/hack.md) documents the new-branch-push-flag.

**Comment by kevgo** [comment]
Thanks for your valuable perspective! You are right, pragmatism beats (at least it should beat) idealism. I'm now convinced that an option to disable tags is a valuable addition to Git Town.

**Comment by kevgo** [comment]
This setting seems specific to individual developers: some people on the team care about Git tags and want the current tags in their local workspace. An example are Ops people. Other people don't care about tags and don't want to sync them. An example are developers who only care about coding. This setting should therefore only be stored in Git metadata and not in `.git-branches.toml`.

**Comment by kevgo** [comment]
First iteration on possible options:

1. sync tags in both directions, let the user resolve conflicts (default)
2. only pull tags (don't push), let the user resolve conflicts
3. only pull tags, remote tags overwrite local tags `git fetch --tags --force`
4. only push tags, let the user resolve conflicts
5. only push tags, local tags overwrite remote tags
6. don't sync any tags

```
(1) git-town.sync-tags = both
(2) git-town.sync-tags = pull
(3) git-town.sync-tags = pull-force
(4) git-town.sync-tags = push
(5) git-town.sync-tags = push-force
(6) git-town.sync-tags = none
```

**Comment by kevgo** [comment]
Additional motivation for not syncing tags in https://github.com/git-town/git-town/issues/2581

**Comment by kevgo** [comment]
Rather than over-engineering this, just provide a setting to disable touching the tags altogether, and leave resolving them up to the user.
