### ISSUE TITLE
Running `git-town set-parent` on perennial or main branch prints unformatted error

### ISSUE THREAD

**Issue by tranhl** [git-town/git-town#3217]
## Description

When running `git-town set-parent` on a main or perennial branch, the [branch name is not substituted](https://github.com/git-town/git-town/blob/d1f8a1158b55c9e2203394f7c926926a1d0c34e6/src/cmd/set_parent.go#L60-L62) in the error message.

## Steps to reproduce

1. Checkout main branch (in my case it is `main`)
2. Run `git-town set-parent`

## Expected

`Error: the branch main is not a feature branch. Only feature branches can have parent branches`

## Actual

`Error: the branch %q is not a feature branch. Only feature branches can have parent branches`

**Comment by kevgo** [comment]
Thanks for reporting this bug!

**Comment by kevgo** [comment]
A fix for this is shipped in v13. Enjoy!
