### ISSUE TITLE
`switch` displays incorrect if `set-parent` was previous used on perennial branch

### ISSUE THREAD

**Issue by tranhl** [git-town/git-town#3218]
Let's say I have a branch called `release-v1.0.0`. Logically speaking it is a perennial branch, but for whatever reason it was not set as a perennial either via `perennial-branches` or `perennial-regex`. If I set its parent to `main`, then Git Town will keep track of it as a feature branch by adding the following to the local Git config file:

```
[git-town-branch "release-v1.0.0"]
	parent = main
```

So according to Git Town, `release-v1.0.0` is considered a feature branch. Now if set `perennial-regex` to `release-.*` and run `gt switch`, I will see this:

```
* main
>   release-v1.0.0


  ↑/k up   ↓/j down   ←/u 10 up   →/d 10 down   enter/o accept   q/esc/ctrl-c abort
```

However, this is technically not correct, as `release-v1.0.0` is perennial and technically shouldn't have a parent anymore. I expect `switch` to show me this instead:

```
* main
> release-v1.0.0


  ↑/k up   ↓/j down   ←/u 10 up   →/d 10 down   enter/o accept   q/esc/ctrl-c abort
```

Which correctly indicates that `release-v1.0.0` is perennial. As part of the `switch` command, perhaps we could clean up branch config from the local Git config file to correctly?

I believe this would be need to be addressed in order to complete #3164 as well, since in case where this happens, what would Git Town consider the branch type for `release-v1.0.0` to be?

**Comment by tranhl** [comment]
FYI for anyone experiencing this - fixing this is as simple as removing the offending `git-town-branch` config item from `.git/config`.

**Comment by kevgo** [comment]
Confirming that this is a bug in `git switch`. If a branch is listed as a perennial branch, it should be treated as such, and any parent branch listed for it should be ignored.

The CLI command to remove the config entry is:

```
git config --unset <entry key>
```

In this case: 

```
git config --unset git-town-branch.release-v1.0.0.parent
```

**Comment by kevgo** [comment]
Rather than ignoring the parent entries in all Git Town commands, the correct course of action seems to remove the wrong parent entries so that they don't cause other problems as well.

**Comment by kevgo** [comment]
This is shipped in v13. Enjoy!
