### ISSUE TITLE
Git town with worktrees issue

### ISSUE THREAD

**Issue by breml** [git-town/git-town#3230]
Last week I tested `git town`. On the repository I tried it, I heavily work with worktrees. While using `git town` on one of the "linked worktree" directories I observed some wired behavior while executing the `sync` command:

* git town complained about not finding some files in `.git/` directory during rebase
* git town ended up closing a PR of a colleague of mine

When I checked #2134 I was under the impression, that it is save to use `git town` with worktrees and in particulary also from "linked worktree" directories and not only from the "main worktree". Can you confirm, that this is the case?

(Unfortunately I no longer have the respective outputs from `git town`, since I closed the respective terminal sessions over the weekend.)

**Comment by kevgo** [comment]
Thanks for reaching out!

> git town complained about not finding some files in .git/ directory during rebase

This sounds like a bug in Git Town, or better missing support for an edge case: rebasing inside a linked worktree. Will fix. Thanks for reporting this!

> When I checked https://github.com/git-town/git-town/issues/2134 I was under the impression, that it is save to use git town with worktrees and in particulary also from "linked worktree" directories and not only from the "main worktree". Can you confirm, that this is the case?

That's the intent. Worktree support is a pretty recent addition, so a number of edge cases that aren't well supported are expected. We rely on feedback from Git Town users like you to identify them, so please keep the bug reports coming.

> git town ended up closing a PR of a colleague of mine

Can you please provide a bit more color around this? What exactly did Git Town do that closed the PR? Did it remove the branch that the PR was for? Did it merge the PR? Thanks!

**Comment by breml** [comment]
@kevgo thanks for your reply, I am glad, that the behavior I observed is in-fact a bug, since it cause some trouble (broken rebase where I first lost some changes, thanks to `git reflog` I was able to recover those; closed PR as already mentioned) for me.

> > git town ended up closing a PR of a colleague of mine
> 
> Can you please provide a bit more color around this? What exactly did Git Town do that closed the PR? Did it remove the branch that the PR was for? Did it merge the PR? Thanks!

On Github I see, that the PR was closed and I see, that I deleted the branch. Both changes have the same timestamp (close and removal of branch) and are ordered by Github in the way I mentioned them (first close then remove of branch). But I think they could well happen the other way round since I suspect, that `git town` removed the branch of my colleague which then caused Github to close the PR (but this is not proved information, since I do not have the console output anymore of the actions, which caused the issue).

**Comment by kevgo** [comment]
Sharing my insights while investigating the issue.

The error happens when [BackendCommands.currentBranchDuringRebase](https://github.com/git-town/git-town/blob/ec36cf093bfa5e814aaeb34e0072a23d98a35006/src/git/backend_commands.go#L428-L440) tries to read files `{root}/.git/rebase-apply/head-name` and `{root}/.git/rebase-merge/head-name`. `{root}` here is the root dir of the current Git repo. On a linked worktree these files do not exist since the linked worktree (correctly) uses the `.git` folder in the main worktree.

The solution is to change `{root}` to the directory of the main worktree. To determine the main worktree, run `git worktree list --porcelain`. A possible output is:

```
worktree /home/kevlar/git-town
HEAD 789caba2da3c4fbcc66dd4a907a28933f9730172
branch refs/heads/kg-linked-worktree-rebase

worktree /home/kevlar/git-town/main
HEAD ec36cf093bfa5e814aaeb34e0072a23d98a35006
branch refs/heads/main
```

The first paragraph is the main worktree. Subsequent paragraphs are linked worktrees. The first line is the directory of the main worktree.

**Comment by kevgo** [comment]
The head name for an ongoing rebase in a linked worktree is at

```
{main worktree dir}/.git/worktrees/{linked worktree}/rebase-merge
```

**Comment by kevgo** [comment]
As of Git 2.18, Git can display the name of the branch being rebased. Assuming we are on a linked worktree and rebase the branch "feature" there, with branch "main" checked out at the main worktree:

```
/t/2/u/development_worktree [(no branch, rebasing feature)] > git branch --list
* (no branch, rebasing feature)
  feature
+ main
```

**Comment by kevgo** [comment]
@breml [v13.0.1](https://github.com/git-town/git-town/releases/tag/v13.0.1) contains a fix for the issue you encountered. I'm curious how it works for you.

**Comment by breml** [comment]
@kevgo I updated to latest version (13.0.2) and I executed `git town sync --verbose` on my broken repository (mentioned above) and `git town still tires to delete my `master` branch with `git push origin :master`. I wonder, if there should be a safety guard to never try to delete main or perennial branches.

**Comment by breml** [comment]
Yesterday I worked with a worktree again and I observed no issues with `git town sync`, so I think this issue is successfully resolved as well.

**Comment by kevgo** [comment]
Great to hear, thanks for confirming that the fix works! 🙏
