### ISSUE TITLE
asks for already known parent branch

### ISSUE THREAD

**Issue by ruudk** [git-town/git-town#3237]
Today I noticed something odd.

I was working on a branch that was already synced using git town.

At some point I thought, I need to move some commits to a prepend branch.

I ran `git town prepend` and create the branch. Later, I synced it and it works fine.

Then I want back the the previous branch. When I ran sync, it asked me what the parent branch should be. 

Well, that should be the one I just prepended. 

I had to manually select it, and then it worked.

But I feel this should be automated.

The description says it should be:

> Creates a new feature branch as the parent of the current branch.
> Syncs the parent branch, cuts a new feature branch with the given name off the parent branch, **makes the new branch the parent of the current branch**, pushes the new feature branch to the origin repository (if "push-new-branches" is true), and brings over all uncommitted changes to the new feature branch.

**Comment by kevgo** [comment]
This sounds like a regression. Thanks for reporting!

**Comment by kevgo** [comment]
If anybody can reproduce this, posting the steps would be super helpful.

**Comment by kevgo** [comment]
I have experienced this a few times as well.

**Comment by kevgo** [comment]
Did you by any chance run the Git Town command from a subdirectory in your Git repo? That causes this issue for me. See #3652.

**Comment by ruudk** [comment]
That could be, but I can't remember

**Comment by kevgo** [comment]
I have just released [v14.2.3](https://github.com/git-town/git-town/releases/tag/v14.2.3) that contains a fix for my currently only hypothesis for this cause of this problem. Given that https://github.com/git-town/git-town/issues/3676 is a duplicate of this issue, I'm closing this one.
