### ISSUE TITLE
git town switch presents already removed branches

### ISSUE THREAD

**Issue by breml** [git-town/git-town#3299]
### Steps to reproduce

1. Have a feature-branch, for which parent is set to master
2. Remove the feature-branch with `git branch -D feature-branch`
3. Run `git town switch`
The already deleted branch can still be seen, selecting the branch obviously leads to an error.

### Command output

```shell
$ git branch -D feature-branch
Deleted branch feature-branch (was f1adf7e46).
$ git town switch

[master] git checkout feature-branch
error: pathspec 'feature-branch' did not match any file(s) known to git
```
```


### Additional information

_No response_

**Comment by kevgo** [comment]
I can reproduce this issue.

**Comment by kevgo** [comment]
This happens because `git town switch` displays all branches that are registered in the Git Town lineage database. Even if that branch no longer exists.

**Comment by kevgo** [comment]
The existing implementation intentionally displays branches listed in the lineage even if they don't exist locally to allow switching to parent branches that aren't checked out locally. 

The implementation isn't quite correct, though, hence this bug: it should only display locally non-existing branches _if they exist remotely_.
