### ISSUE TITLE
[Feature Request] `git town stack list` command

### ISSUE THREAD

**Issue by WhosNickDoglio** [git-town/git-town#3303]
Just stumbled upon this awesome library the other day and very excited to start using it. 

I've been using [git-chain](https://github.com/Shopify/git-chain) to help me work with stacked/chain branches and as I migrate to start using Git Town something I miss is the `git chain list` command which just prints out all the current chained branches. 

Here's an example of it's output: 
<img width="2141" alt="Screenshot 2024-04-07 at 10 50 07 PM" src="https://github.com/git-town/git-town/assets/3968678/183811e3-c036-41ab-a2dd-1515395a4a8f">

It would be great if there was a command that worked similiarly so I could keep track of the order of all my stacked branches

**Comment by kevgo** [comment]
Thanks for sharing git-chain, great tool! Git Town can do everything git-chain does but more convenient. Check out [stacked changes support](https://www.git-town.com/stacked-changes) for an overview of the commands to incrementally create branch stacks (chains), insert new branches at the end or in the middle, remove branches from the chain, sync/rebase chains, etc. 

Two Git Town commands display the current stack (chains) and their branches:

- [git town switch](https://www.git-town.com/commands/switch) shows all branches and their hierarchy, and allows you to switch branches using cursor or VIM motion keys
- [git town config](https://www.git-town.com/commands/config) shows the configured branch hierarchy, together with other config data

I use `git town switch` many times per day to switch branches.

**Comment by kevgo** [comment]
Closing this ticket as "works already". If you have additional feedback, please feel free to comment or re-open this ticket. Thanks!
