### ISSUE TITLE
sync fails when origin/main branch and local dev branch are both changed

### ISSUE THREAD

**Issue by pjh** [git-town/git-town#3308]
### Steps to reproduce

1. Create and clone a new github repository (e.g. https://github.com/pjh/git-town)
2. Create a new branch `branch1`, add a commit, and create a pull request:

```
$ git branch -v
* main 135fe9870e64 Initial commit

$ git town hack branch1

[main] git fetch --prune --tags
Git Town needs to be configured

? Please specify the main development branch:  [Use arrows to move, enter to select, type to fil
? Please specify the main development branch: main

[main] git rebase origin/main
Current branch main is up to date.

[main] git branch branch1 main

[main] git checkout branch1
Switched to branch 'branch1'

$ echo "# git-town" > README.md

$ git add README.md

$ git commit -m "Add README"
[branch1 f9d8e1315d30] Add README
 1 file changed, 1 insertion(+)
 create mode 100644 README.md

$ git town propose

[branch1] git fetch --prune --tags

[branch1] git checkout main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.

[main] git rebase origin/main
Current branch main is up to date.

[main] git checkout branch1
Switched to branch 'branch1'

[branch1] git merge --no-edit main
Already up to date.

[branch1] git push -u origin branch1
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 16 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 515 bytes | 515.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
remote:
remote: Create a pull request for 'branch1' on GitHub by visiting:
remote:      https://github.com/pjh/git-town/pull/new/branch1
remote:
To github.com:pjh/git-town.git
 * [new branch]                branch1 -> branch1
branch 'branch1' set up to track 'origin/branch1'.

xdg-open https://github.com/pjh/git-town/compare/branch1?expand=1
```

3. In a second clone of the repository, create a pull request and merge a commit to main (e.g. https://github.com/pjh/git-town/pull/2).
4. In the first clone of the repository, add a commit to `branch1` for the first PR:

```
$ echo "" >> README.md ; echo "git towwwwwwwn" >> README.md

$ git commit -a -m "Add more README text"
[branch1 3fc2de69aa8e] Add more README text
 1 file changed, 2 insertions(+)

$ git log
commit 3fc2de69aa8e9e9deb68626d82847ee6bc760e2c (HEAD -> branch1)
Author: Peter Hornyack <peterhornyack@google.com>
Date:   Wed Apr 10 14:33:49 2024 -0700

    Add more README text

commit f9d8e1315d30ad4cd93da50fdd905159a21fad21 (origin/branch1)
Author: Peter Hornyack <peterhornyack@google.com>
Date:   Wed Apr 10 14:28:53 2024 -0700

    Add README

commit 135fe9870e6420b16f6b9b052586b1f35c90902b (origin/main, origin/HEAD, main)
Author: Peter Hornyack <peterhornyack@google.com>
Date:   Wed Apr 10 14:25:52 2024 -0700

    Initial commit
```

5. Run `git town sync` to attempt to update the first PR. My expectation is that git town will first update the `main` branch to match `origin/main`, then merge `main` into `branch1` and push `branch1` to update the PR. The result is that the sync command fails (and then an undo also fails).

### Command output

$ git town sync

[branch1] git fetch --prune --tags
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 7 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), 6.00 KiB | 3.00 MiB/s, done.
From github.com:pjh/git-town
 * [new branch]                banana     -> origin/banana
   135fe9870e64..bd2f0a192fea  main       -> origin/main

[branch1] git checkout main
Switched to branch 'main'
Your branch is behind 'origin/main' by 2 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

[main] git push -u origin main
To github.com:pjh/git-town.git
 ! [rejected]                  main -> main (non-fast-forward)
error: failed to push some refs to 'github.com:pjh/git-town.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. If you want to integrate the remote changes,
hint: use 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Error: exit status 1

To go back to where you started, run "git-town undo".
To continue after having resolved conflicts, run "git-town continue".
To continue by skipping the current branch, run "git-town skip".

$ git town undo

[main] git push origin :main
To github.com:pjh/git-town.git
 ! [remote rejected]           main (refusing to delete the current branch: refs/heads/main)
error: failed to push some refs to 'github.com:pjh/git-town.git'

Error: exit status 1To continue by skipping the current branch, run "git-town skip".

### Additional information

```
$ git town --version
Git Town v10.0.3 (2023-12-12)

$ git town config

Branches:
  main branch: main
  perennial branches: (not set)

Configuration:
  offline: no
  run pre-push hook: yes
  push new branches: no
  ship removes the remote branch: yes
  sync-feature strategy: merge
  sync-perennial strategy: rebase
  sync with upstream: yes
  sync before shipping: no

Hosting:
  hosting service override: (not set)
  GitHub token: (not set)
  GitLab token: (not set)
  Gitea token: (not set)

Branch Lineage:
  main
    branch1
```

git config: https://gist.github.com/pjh/6d28246d5f92ec7c5459c7a45dd7e1af

**Comment by pjh** [comment]
It's very unexpected to me that git-town would ever try to run `[main] git push -u origin main` 😕

**Comment by pjh** [comment]
I recovered from the failed command by running `git town switch` and choosing "Discard the unfinished state and run the new command". I then ran the sync command again with the --verbose flag and it failed in the same way, [here's the output](https://gist.github.com/pjh/d14dc34bb9663c694192b6fdd1950619).

**Comment by pjh** [comment]
Sigh, nevermind I think, I updated to `Git Town 13.0.2` and it looks like this no longer happens.

**Comment by kevgo** [comment]
Thanks for taking the time to submit this detailed bug report! If I understand you correctly, you:
- create feature branch `branch1` with a commit `Add README`
- ship feature branch `banana` separately, resulting in a new commit `Add banana file` on `origin/main`
- add another commit `Add more README text` to `branch1`
- run `git town sync` on feature branch 1

This (pretty straightforward) use case is covered by this end-to-end test: https://github.com/git-town/git-town/blob/main/features/sync/current_branch/feature_branch/merge_sync_strategy/tracking_branch/with/happy_path.feature.

As you correctly expected, Git Town first updates the main branch with new commits from its tracking branch, then updates the feature branch with new commits from its tracking branch, then merges the updated main branch into your updated feature branch.

**Comment by pjh** [comment]
I wonder if the behavior that I saw here was due to non-default git branch sorting, as described in https://github.com/git-town/git-town/issues/3241#issuecomment-2027607725. I use `branch.sort=-committerdate` in my git config. Updating to git-town [v13.0.2](https://github.com/git-town/git-town/releases/tag/v13.0.2) with the `git branch -vva --sort=refname` fix resolved this behavior.

**Comment by kevgo** [comment]
I also think that was the reason. The symptoms (trying to re-push the master branch) and the cure (v13.0.2) fit perfectly.
