### ISSUE TITLE
Unmet expectations with `set-parent`

### ISSUE THREAD

**Issue by matthewgonzalez** [git-town/git-town#3473]
If I have a hypothetical stack of branches and move a child up the stack using `set-parent`, all of the commits the child branch inherited from the previous tree remain.

My expectations are that any commits that were associated with the former parent branches would no longer show up in the branch's commit history, considering it's no longer a child of those parent branches.

I understand this is not a trivial ask, but am curious to know if I'm off-base.

**Comment by kevgo** [comment]
That's a great idea! The implementation could be similar to https://github.com/git-town/git-town/issues/2388.

**Comment by kevgo** [comment]
This sounds more like [stack refactoring](https://github.com/git-town/git-town/issues/3338).

**Comment by matthewgonzalez** [comment]
Thanks! Looking forward to the progress made on this; will keep an eye on it!

**Comment by kevgo** [comment]
This functionality might be achievable using `git rebase --onto`. If anyone has experience doing this manually, it would be super helpful to share the exact Git commands that `git town set-parent` should execute. Appreciate the input, thanks!

**Comment by kevgo** [comment]
This is now available in [Git Town 17](https://github.com/git-town/git-town/releases/tag/v17.0.0). Enjoy!
