### ISSUE TITLE
git town requires user name and email to be defined in global config

### ISSUE THREAD

**Issue by kelbyers** [git-town/git-town#3614]
### Steps to reproduce

I have my user name and email defined in config files that get included into my main `~/.gitconfig` file.

E.g.:
```
# cat ~/.gitconfig.user
[user]
	name = User Name
	email = user1@example.com
```

Then in my `~/.gitconfig`:
```
[include]
	path = .gitconfig.user
```

If I run `git config user.email`, it correctly finds my email (or user.name). Running `git config --global user.email` does not return it.

Running any `git town` sub-command complains about the "missing" config. Trying to create new branches with `git town hack` does not create the new branch.

### Command output

```shell
❯ git town hack --verbose junk1

(verbose) git version
git version 2.45.2

(verbose) git config -lz --global
core.excludesfile
~/.gitignore_globalcore.quotepath
falsecore.commitgraph
truecommit.template
~/.stCommitMsginclude.path
~/.gitconfig.userinclude.path
~/.gitconfig.localpull.ff
onlygc.writecommitgraph
trueinit.defaultbranch
main
(verbose) git config -lz --local
core.repositoryformatversion
0core.filemode
truecore.bare
falsecore.logallrefupdates
truecore.ignorecase
truecore.precomposeunicode
truesubmodule.active
.remote.origin.url
https://github.com/one-thd/platform-audit-report-tool-uiremote.origin.fetch
+refs/heads/*:refs/remotes/origin/*branch.main.remote
originbranch.main.merge
refs/heads/maingit-town.main-branch
vite-vue3git-town.perennial-branches
maingit-town-branch.playwright.parent
vite-vue3branch.playwright.vscode-merge-base
origin/vite-vue3branch.playwright.remote
originbranch.playwright.merge
refs/heads/playwrightbranch.integration.remote
originbranch.integration.merge
refs/heads/integrationbranch.debug-nginx.remote
originbranch.debug-nginx.merge
refs/heads/debug-nginx
(verbose) git rev-parse --show-toplevel
/Users/jxb2016/git/one-thd/dope/platform-audit-report-tool-ui

(verbose) git rev-parse --verify --abbrev-ref @{-1}
debug-nginx

(verbose) git status --long --ignore-submodules
On branch integration
Your branch is up to date with 'origin/integration'.

nothing to commit, working tree clean

(verbose) git remote
origin

(verbose) git rev-parse --abbrev-ref HEAD
integration

[integration] git fetch --prune --tags

(verbose) git stash list

(verbose) git branch -vva --sort=refname
  debug-nginx                5a4b59f [origin/debug-nginx: gone] debug nginx docker startup
* integration                e8e2d83 [origin/integration] Merge pull request #58 from one-thd/debug-nginx
  main                       87c9978 [origin/main] Merge pull request #36 from one-thd/remove-GCP-deployments
  playwright                 b4606b7 [origin/playwright] play around with playwright
  remotes/origin/HEAD        -> origin/main
  remotes/origin/integration e8e2d83 Merge pull request #58 from one-thd/debug-nginx
  remotes/origin/main        87c9978 Merge pull request #36 from one-thd/remove-GCP-deployments
  remotes/origin/playwright  b4606b7 play around with playwright

Error: please set the Git user email by running: git config --global user.email "<your email>"
```

### Additional information

All the `git town` commands worked with my configuration until a recent update of `git-town`

```
❯ git town --version
Git Town 14.2.1
```

**Comment by kevgo** [comment]
Thanks for reporting this bug! For what it's worth, this probably never worked correctly and you just never ran into a situation where that problem surfaced. The recent Git Town update merely tightens Git Town's error handling, so this problem gets reported correctly in all situations now.

According to [the commit to Git that introduces this feature](https://github.com/gitster/git/commit/9b25a0b52e09400719366f0a33d0d0da98bbf7b0) and [the docs](https://git-scm.com/docs/git-config#Documentation/git-config.txt---no-includes), Git doesn't follow the include directive when being asked to read a specific config file for backwards compatibility reasons. To enable following includes in this situation, one needs to add the `--includes` switch. #3615 adds this to Git Town.

Btw thanks for sharing this neat trick about [extracting parts of the Git configuration into external files](https://git-scm.com/docs/git-config#_includes)! That's exactly what I need for my own Git configuration. 🙏

**Comment by kevgo** [comment]
@kelbyers [v14.2.2](https://github.com/git-town/git-town/releases/tag/v14.2.2) ships the fix for this.
