### ISSUE TITLE
Introduce `git town get-parent`

### ISSUE THREAD

**Issue by ruudk** [git-town/git-town#3628]
### Your message to us

It would be great to programmatically read out the parent of a stacked PR.

Example:
```command
$ git town get-parent
some-parent-branch
```

**Comment by kevgo** [comment]
Agree, this would be useful for scripting! Not sure this feature is big enough to justify making it a top-level command in Git Town. I see this rarely executed manually on the CLI, this seems used mostly inside Bash scripts. So we could nest this command under `git town config`.

Some quick readme-driven development to get a feel for how the CLI experience could look like:

```bash
# print the parent of the current branch
> git town config parent
parent-branch

# print the parent of the given branch
> git town config parent my-branch
parent-branch
```

After #1286 is implemented:

```bash
# print the parents of the current branch
> git town config parents
parent-branch-1
parent-branch-2

# print the parent of the given branch
> git town config parents my-branch
parent-branch-1
parent-branch-2
```

**Comment by ruudk** [comment]
Now that https://github.com/git-town/git-town/issues/1286 is closed, can this be done simpler?

I agree that this can be part of the config. No need for top-level.

Do you have an idea how to get this rolling? I might be able to contribute.

**Comment by kevgo** [comment]
@ruudk I ended up following your suggestion and calling this command `git town config get-parent` to distinguish it from `git town set-parent`.

**Comment by ruudk** [comment]
Thank you so much! Once it's released I'm going to test it out in my script 🤩

**Comment by kevgo** [comment]
Implementing this was easier than explaining how to do it... and since you are a sponsor, I just went ahead and did it. Will release today or tomorrow after #3207 is done as well.

**Comment by kevgo** [comment]
This is now shipped in [v14.3.0](https://github.com/git-town/git-town/releases/tag/v14.3.0). Enjoy!

**Comment by ruudk** [comment]
Is there a reason for the extra newline at the end?

```command
$ git town config get-parent
main

```

I feel it should be:
```command
$ git town config get-parent
main
```

**Comment by kevgo** [comment]
#3717 fixes the redundant empty line in the output.

**Comment by kevgo** [comment]
This is released now.

**Comment by ruudk** [comment]
Thanks, it works perfectly now!
