### ISSUE TITLE
Automatically rebase with `--autosquash` to merge `fixup!` commits

### ISSUE THREAD

**Issue by ruudk** [git-town/git-town#3659]
### Your message to us

There is a [great feature in Git](https://www.30secondsofcode.org/git/s/create-fixup-commit) that allows you to create new commits that should be fixed up in previous commits.

In [Tower for Mac](https://www.git-tower.com/mac) this is very easily by typing `fixup!` in the commit message and it will show an autocomplete dropdown to reference previous commits.

You then commit it and it shows an `Autosquash` button to merge those commits with the targets.

It's very easy to forget to autosquash and then pushing the `fixup!` commits to the branch. Even worse, if you put those in `main`, you're kind of screwed.

So I was thinking, can't Git Town handle this? When I call `git town sync`, it should rebase with `--autosquash` so that it's always done.

**Comment by kevgo** [comment]
Thanks for sharing about the `--autosquash` option, I wasn't aware of it! Seems a useful addition to `git sync`, assuming it doesn't have any other side effects.

**Comment by kevgo** [comment]
According to [this blog post](https://thoughtbot.com/blog/autosquashing-git-commits) you can tell Git to always autosquash on every rebase:

```
git config --global rebase.autosquash true
```

The advantage of configuring Git this way are that it applies to all rebases, even those you perform manually outside of Git Town. I feel like that's a better and more generic solution. Git Town shouldn't reimplement features that Git already provides.

Does using this Git config setting work for your use case?

**Comment by ruudk** [comment]
That's even better! I will try that next week and let you know! Thanks 🥳

**Comment by ruudk** [comment]
I tried it, but it doesn't work together with `sync`. 

It seems that `sync` just ignores it. 

But we can close this, I can automate this in my own sync script.

**Comment by kevgo** [comment]
Thanks for the useful feedback and for keeping the issue tracker clean!  🙏
