### ISSUE TITLE
How to programmatically detect when Git Town is syncing?

### ISSUE THREAD

**Issue by ruudk** [git-town/git-town#3668]
### Your message to us

I have a file watcher that sometimes goes crazy when I do a sync.

Does Git Town write a status file somewhere that I can use to make sure I don't perform operations on `git town sync`?

**Comment by kevgo** [comment]
No, Git Town doesn't create a temporary status file while running.

Can you create a Bash or Powershell script that pauses your file watcher, runs `git town sync`, and then re-enables the watcher?

**Comment by ruudk** [comment]
Why didn't I think of that! So simple and pragmatic 🤩. Thanks.
