### ISSUE TITLE
Allow setting perennial-regex with negative lookahead

### ISSUE THREAD

**Issue by ruudk** [git-town/git-town#3683]
### Your message to us

**First of all, thanks for making this wonderful tool. I know I have been raising a few issues the last days but that's because I use this tool intensively and already can't live without it 💙** 

In my setup, I use prefixes for my short lived branches that start with `ruudk/`.

I'd like to configure Town so that `main` and anything that does not start with `ruudk/` is a perennial branch.

Is that possible?

It tried to use a negative lookahead but it didn't work.

```
perennial-regex = ^(?!ruudk).*$
```
results in:
> Error in perennial regex "^(?!ruudk).*$": error parsing regexp: invalid or unsupported Perl syntax: `(?!`

```
perennial-regex = (?!ruudk).*
```
results in:
> Error in perennial regex "(?!ruudk).*": error parsing regexp: invalid or unsupported Perl syntax: `(?!`

Is this possible? If so, it would be great to document this in the great documentation.

**Comment by kevgo** [comment]
I don't see a way to configure this right now either.

One possible implementation could be to add regex config settings similar to [perennial-regex](https://www.git-town.com/preferences/perennial-regex) for other branch types: `feature-regex`, `observed-regex`, and `contribution-regex`.

Additionally, we could introduce a config setting `default-branch-type` to define the branch type when none of the above regexes match.

Although this approach would add quite a few additional config settings, it would likely still be intuitive enough for most people to understand quickly.

**Comment by kevgo** [comment]
- [ ] config setting `feature-regex`
- [ ] config setting `observed-regex`
- [ ] config setting `contribution-regex`
- [ ] config setting `parked-regex`
- [ ] config setting `prototype-regex`
- [ ] config setting `default-branch-type` that defines the default branch type to assume for branches that aren't listed as a dedicated branch type and don't match any other regexes
   - possible values: `feature`, `perennial`, `observed`, `contribution`, `parked`, `prototype`
   - default: `feature`

**Comment by kevgo** [comment]
Minimal feature set for the first iteration on this: 

- [ ] `default-branch-type` setting
- [ ] `feature-regex` setting

This allows replacing the current default of "all branches are feature branches unless specified otherwise" with "all branches are observed unless specified otherwise, and here is the regex for branches that I own". This would implement the ask of this ticket.

**Comment by kevgo** [comment]
Open question: how does the user see that all branches have the correct type? Probably best by listing all local branches and their types?

`git town config` is for displaying what is configured, not the actual branches in the workspace, so that's probably not the right place

Possible options to list all branches and their types:

- `git town switch --branch-types`
- `git town config branch-types`

**Comment by kevgo** [comment]
@ruudk thanks for submitting this really useful feature request. It turned into a real killer feature, which is now available in [v16.1](https://github.com/git-town/git-town/releases/tag/v16.1.0). You can now configure Git Town to treat branches whose name doesn't start with `ruudk/` as any type. I think [observed branches](https://www.git-town.com/branch-types#observed-branches) might be a good fit? Enjoy!

**Comment by kevgo** [comment]
To check whether the new setup works you can run `git town switch --type=feature` to see which branches are now feature branches.

**Comment by ruudk** [comment]
Thank you for this! I i just configured it like this:
```
git config --global git-town.default-branch-type "observed"
git config --global git-town.feature-regex '^ruudk\/.*'
```

And will test it out 😁

**Comment by kevgo** [comment]
Looks great! To test it out, you can use the command `git town switch --type observed` (or the shorthand `git town switch -to`). This will switch only between your observed branches.

**Comment by ruudk** [comment]
It works, thanks!
