### ISSUE TITLE
Sync should update the PR base branch when parent was changed using `set-parent`

### ISSUE THREAD

**Issue by ruudk** [git-town/git-town#3723]
### Your message to us

When you manually change the parent of a branch that has already been synced (and proposed as Pull Request), it should update the target branch when doing the next sync.

**Comment by kevgo** [comment]
That's an important missing feature. https://github.com/git-town/git-town/issues/2745 outlines the bigger idea behind it. Closing this ticket as duplicate. Let's continue talking about this on the other ticket! 🙂

**Comment by kevgo** [comment]
This is now available in [v16.3](https://github.com/git-town/git-town/releases/tag/v16.3.0).
