### ISSUE TITLE
[Feature] Integrate fzf into git-town switch 

### ISSUE THREAD

**Issue by zodman** [git-town/git-town#3824]
### Your message to us

please! https://github.com/junegunn/fzf

**Comment by kevgo** [comment]
Are you currently using fzf with vanilla Git, as described [here](https://medium.com/@mrWinston/smarter-git-checkout-using-fzf-to-supercharge-your-commandline-7507db600996)? Does the linked solution work for you? If not, what's missing that Git Town could add?

One challenge I foresee with using fzf to filter down the list of branches is that the hierarchy information will get removed and mess up the output. Let's say we have these branches:

```
main
  feature-1
    feature-1a-foo
    feature-1b-bar
  feature-2-foo
    feature-2a-baz
    feature-2b-qux
```

When I filter by `foo`, it would display this:

```
    feature-1a-foo
  feature-2-foo
```

I'm concerned that the inconsistent indentation in this presentation is not helpful anymore and looks like an error. It's no longer clear what their parent branches are or what stack each branch belongs to. It would be better to print it without indentation:

```
feature-1a-foo
feature-2-foo
```

That's exactly what you get when integrating fzf with vanilla Git, as mentioned above.

**Comment by zodman** [comment]
yeah, I forget the need of using nesting, that doesn't work for fzf...

Could be filtering the branch for selecting its something useful, I use a lot of branches of others I need filtering instead of scroll down ..

**Comment by kevgo** [comment]
You can scroll much faster by pressing `u` to go up 10 entries and `d` to go down 10 entries.
If that's still not enough for you, I suggest combining fzf with the regular `git branch` command, as described [here](https://medium.com/@mrWinston/smarter-git-checkout-using-fzf-to-supercharge-your-commandline-7507db600996).

**Comment by kevgo** [comment]
Thank you for submitting this idea! After careful consideration, I've decided to close this ticket. The integration of fzf directly with `git branch` offers a more streamlined approach than implementing it within Git Town. This keeps the focus on Git Town’s core features while allowing users to leverage existing tools more effectively.
