### ISSUE TITLE
git town switch  - Confusing behaviour when there are new local branches

### ISSUE THREAD

**Issue by antoineMoPa** [git-town/git-town#3909]
To explain the confusing behaviour, here's my workflow: I'm used to switch between my branches multiple times a day with `git town switch`. Usually, I see the interface to navigate to a branch and I don't really have to think while using `git town switch`. (I even have an alias `alias gts='git-town switch'`)

Sometimes I review a teammate's PR with `git fetch branch-name`, then `git switch branch-name`. After this point, I might go for lunch or whatever and when I come back, the behaviour of `git town switch` will be different (it will ask me for a parent for that branch I previously reviewed). However, at this point I'm expecting to navigate between branches, so I invariably set the wrong parent to this branch I previously reviewed. This is not helped by the fact that the UI is very similar for both navigating and selecting parent branches.

In general, I don't care about setting the parent for branches I'm just reviewing. If git-town would just ignore these, that would be great. Is there a way to disable this behaviour or a better workflow you know about? Or could it just default to the main branch?

**Comment by kevgo** [comment]
Thanks for reaching out! Great to hear you’re finding git town switch useful. Git Town has a feature that fits your use case perfectly. When you check out a teammate’s branch with `git observe branch-name` (or `git town observe branch-name` if you haven’t set up the alias), it registers the branch as an [observed branch](https://www.git-town.com/branch-types#observed-branches) on your machine. This means Git Town won’t prompt you about its parent anymore.

Even better, when you run `git sync` on an observed branch (or `git sync --all` on any branch), Git Town syncs the branch knowing that you are just observing and not contributing to it:

- It pulls updates your teammate made to the branch down to your machine.
- It doesn’t pull in updates from the parent branch into this branch. Syncing with the parent is your teammate’s job; you’re just reviewing.
- It doesn’t push any local commits you made, like those for testing during code review.

More info at https://www.git-town.com/commands/observe.

Hope this helps! Let me know if you have any other questions.

**Comment by antoineMoPa** [comment]
@kevgo thanks for the quick reply, I'll integrate `observe` to my workflow 💜
