### ISSUE TITLE
remove the "sync-perennial-strategy"

### ISSUE THREAD

**Issue by kevgo** [git-town/git-town#3914]
It was only introduced to match the first screencast. There is only one valid value here: rebase.

There is not only no point letting users configure this, it's actively harmful and expensive.

**Comment by kevgo** [comment]
This is blocking on releasing the new screencasts.

**Comment by kevgo** [comment]
This doesn't need to be breaking if https://github.com/git-town/git-town/issues/3866 provides an automatic upgrade for the config file.

**Comment by sergej-koscejev** [comment]
Can there be a setting like fast-forward-only? My perennial branches are protected on GitHub and I shouldn’t have any commits on the perennial branches directly. I also don’t want git town to push them but that might be another discussion.

**Comment by kevgo** [comment]
That's a great idea! And a great reason to keep this setting. It might also help with #2224.

**Comment by kevgo** [comment]
The natural name for this sync strategy would be `ff-only`.

If the user runs into the situation where there is a disallowed unpushed local commit on a perennial branch, they can run `git town skip` to not sync that branch, finish the sync, and then move the unpushed local commit to another branch.

**Comment by kevgo** [comment]
Closing this issue since its original idea is now obsolete and we don't want to change what tickets are about. I have created #4104 to plan the new idea of a `ff-only` or `no-local-commits` sync strategy.
