### ISSUE TITLE
`git town switch` should display the branch type

### ISSUE THREAD

**Issue by kevgo** [git-town/git-town#3937]
Format it like https://github.com/git-town/git-town/issues/3807#issuecomment-2330218849

**Comment by kevgo** [comment]
I just built this, looks pretty busy.

<img width="686" alt="Screenshot 2024-09-11 at 4 30 44 PM" src="https://github.com/user-attachments/assets/ab4f7e38-0261-4c6d-956a-22d4287b8541">

**Comment by stephenwade** [comment]
I think most branches will be feature branches, so we don't need to show `(feature)`. Maybe that will make it feel less busy?

See https://github.com/git-town/git-town/issues/3807#issuecomment-2330218849:

<img width="317" alt="Screenshot 2024-09-04 at 5 59 44 PM" src="https://github.com/user-attachments/assets/1be0ca34-56ed-4d99-be23-1d0e7d60f8cf">

**Comment by stephenwade** [comment]
Same for `(main)`. The user should know which branch is their main.

**Comment by kevgo** [comment]
Really good ideas!

**Comment by kevgo** [comment]
This is now available as part of [Git Town 16.2](https://github.com/git-town/git-town/releases/tag/v16.2.0). Enjoy!
