### ISSUE TITLE
switch: `--up` and `--down` flags

### ISSUE THREAD

**Issue by kevgo** [git-town/git-town#3974]
`--up` flag: when given, checks out the parent branch.
`--down` flag: when given, checks out the child branch.

**Comment by stephenwade** [comment]
What happens if there are multiple child branches?

**Comment by kevgo** [comment]
Good question. Git Town could either:

1. print an error message and do nothing
2. let the user choose the child branch to check out (using the UI from `git town switch`)
3. check out the first child

I think option 2 makes the most sense here.

**Comment by kevgo** [comment]
Closing this idea as "not planned". I think the normal behavior of `git town switch` is almost always the better user experience. I can't think of a situation where switching a branch up and down would be more useful than seeing the entire stack and moving up and down there.
