### ISSUE TITLE
Feature request and use case for team-wide contribution branches

### ISSUE THREAD

**Issue by stephenwade** [git-town/git-town#3985]
### Your message to us

From the ["contribution-branches" website page](https://www.git-town.com/preferences/contribution-branches):

> The [Git Town configuration file](https://www.git-town.com/configuration-file) does not define team-wide contribution branches because one developer's feature branch is another developer's contribution or observed branch.

At work, we use [Renovate](https://docs.renovatebot.com/) to help with package updates. I want to set all branches whose names start with "renovate/" to be contribution branches for all team members.

**Comment by kevgo** [comment]
Thanks for sharing this. I was looking for a reason to add a `contribution-regex` setting. Now there is one!

**Comment by ruudk** [comment]
Would it make sense to propose renovate and dependabot prefixes as global defaults?

**Comment by kevgo** [comment]
Would you default them to observed or contribution branches?

**Comment by ruudk** [comment]
Good question. I thought they should be contribution... but that is not ideal. Sometimes you need to manually fix something in a Dependabot PR and rebase it. So therefore observed makes more sense.

**Comment by stephenwade** [comment]
@ruudk Doesn't contribution make more sense?

> Contribution branches are for people who contribute commits to somebody else's feature branch.

> Observed branches are for people who want to observe the work of somebody else without contributing commits to it.

https://www.git-town.com/branch-types

**Comment by ruudk** [comment]
No, because when you checkout a Dependabot PR , it's often to fix things that broke. So you need to be able to commit changes and/or rebase.

**Comment by ruudk** [comment]
Maybe I'm confused. I just configured it like suggested:
```command
git config --global --unset git-town.observed-regex
git config --global git-town.contribution-regex "^dependabot/"
```
and will test it out in the coming days / weeks.
