### ISSUE TITLE
rename "git town rename-branch" to "git town rename"

### ISSUE THREAD

**Issue by kevgo** [git-town/git-town#4038]

**Comment by kevgo** [comment]
On the other hand, pretty much all Git Town commands are about branches. So why group this one only?

**Comment by stephenwade** [comment]
It would be reasonable to rename "git town rename-branch" to "git town rename".

Like you said, most Git Town commands are about branches.

- `git town hack` (on a new branch)
- `git town sync` (the current branch)
- `git town switch` (to another branch)
- `git town ship` (the current branch)
- `git town kill` (the current branch)

Why not `git town rename` (the current branch)?

**Comment by kevgo** [comment]
Great idea!

**Comment by bengeois** [comment]
I was thinking the same today when using this command. I can propose a PR if you're up to ?

**Comment by kevgo** [comment]
Yes, please do! All contributions are very welcome no matter how big or small! All the tickets listed here are actionable unless they have the `idea stage` tag.
