### ISSUE TITLE
[wishlist] Automatically add merge request dependencies

### ISSUE THREAD

**Issue by vectro** [git-town/git-town#4131]
### Your message to us

When creating stacked MRs in GitLab using git-town, it would be nice if Git Town were to automatically add a merge request dependency, so that the child branch cannot be merged before the parent branch. Probably this is only desired if the parent branch is not perennial.

See also GitLab documentation: https://docs.gitlab.com/ee/user/project/merge_requests/dependencies.html

**Comment by kevgo** [comment]
Dependent merge requests are a cool feature! Currently, the `git town propose` command simply opens the webpage for creating a new proposal, but many code forges allow pre-populating some fields via URL arguments. 

For example, GitHub allows pre-filling the title and body of a pull request like this:<br> `https://github.com/git-town/git-town/compare/feature?expand=1&title=my_title&body=my_body`. 

Do you know if there's a similar way to include the ID or URL of a dependent merge request in the URL for creating new MRs on GitLab?

**Comment by vectro** [comment]
Unfortunately it doesn't look like it's possible to create dependencies via the URL, or even the create merge request API. Rather one would have to make a separate API POST call, which seems out of scope for git-town.
