### ISSUE TITLE
handle signals more gracefully

### ISSUE THREAD

**Issue by allewun** [git-town/git-town#414]
I was performing a `git ship` when the "push" step stalled for a long time (ssh/server issue). I sent a `^C`, which ended the ship abruptly.

I think we can do a bit better by [trapping](http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_12_02.html) the signal. We should show the user what steps were not completed, so they can finish it manually after aborting. In my case, I still had to perform the push myself and cleanup my branches.

Taking it one step further, we could have a `--retry` mechanism that knows where it left off the first time.

**Comment by kevgo** [comment]
:+1:  I like both ideas

**Comment by allewun** [comment]
Any ideas how I can test killing a script mid-execution?

**Comment by kevgo** [comment]
Good thing that our specs are in Ruby. `Process.kill("INT", pid)` seems to be the ticket here.

If this is hard to test, I think its fine without tests though. The specs wouldn't be very deterministic given that we have to wait a fixed amount of time before killing the subprocess.

**Comment by kevgo** [comment]
Catching signals in Go:

```go
signals := make(chan os.Signal, 1)
signal.Notify(signals, os.Interrupt)

server := NewServer()
server.Run()

select {
  case <-signals:
    server.Shutdown()
}
```

**Comment by kevgo** [comment]
The Go-based implementation traps Ctrl-C now.

**Comment by allewun** [comment]
Wow 9 years ago!

**Comment by kevgo** [comment]
Better late than never!
