### ISSUE TITLE
git propose: unsupported hosting platform

### ISSUE THREAD

**Issue by ruudk** [git-town/git-town#4165]
### Steps to reproduce

When doing OSS contributions I often setup 2 remotes:

```command
$ git remote
fork
upstream
```

But as soon as I do `git town propose` I get

```command
$ git town propose

Error: unsupported hosting platform

This command requires hosting on one of these services:
* Bitbucket
* GitHub
* GitLab
* Gitea
```

Why is this?

### Command output

```shell
It works fine on projects with just 1 remote.
```

**Comment by kevgo** [comment]
I think that's because Git Town uses the `origin` remote to determine the hosting platform. If no such remote exists, Git Town currently stops and gives up. 

One way to make it work better in situations like the one you describe would be to use the `upstream` remote if there is no origin remote.

**Comment by ruudk** [comment]
Why can't it use the first one it finds?

**Comment by kevgo** [comment]
The thinking was to use the platform on which the pull requests gets made. In case different remotes are on different platforms.

Admittedly that's a highly unlikely scenario. 

Technically we could use the remote embedded in the name of the tracking branch of the current branch or the first ancestor branch that has a tracking branch.  

If none of that yields any result, 
you make a good point that Git Town could just use the first available remote, and that would be correct in almost all cases.

**Comment by kevgo** [comment]
As part of syncing, Git Town might need to create tracking branches at the remote. When it does that, it currently runs this command: `git push -u origin <branch>`. With the remote setup above, `origin` would need to be replaced with another remote name. Which remote should Git Town push the branch to in this case? My best guess is "the remote at which other tracking branches exist". This information might not exist if there are no branches. Also, there might be remote branches at different remotes.

**Comment by stephenwade** [comment]
Suggestion: Ask the user and/or create a config setting for which remote to use (that defaults to "origin").

**Comment by kevgo** [comment]
Yeah that might be the best way forward here. I was thinking we could use the remote that the main branch uses, but a config option would be better because it also helps in use cases like #1181.

**Comment by kevgo** [comment]
After thinking about this a few more days, this definitely needs to be a config option. There are too many edge cases that prevent detecting this automatically in a reliable way. 

While we are at it, let's make the `upstream` remote configurable as well.

Idea for how to represent this in the config file:

```toml
[remotes]
dev = "origin"
upstream = "upstream"
```

**Comment by kevgo** [comment]
Yes, configuration can be per project. If you can't add a config file, for example because you work on a fork of an open-source project, you would (in the future) configure this in Git metadata:

```
git config git-town.remotes.dev fork
```

**Comment by kevgo** [comment]
Removing the `bug` label since lack of support for custom remote names is a missing feature. Marking it as potentially a breaking because addressing this will require introducing a new term or concept to replace the current use of `origin`.

**Comment by kevgo** [comment]
Examples for existing things that would need to be renamed: config setting `hosting-origin-hostname` would no longer make sense when there is a `remotes.dev` config setting. It would need to be renamed to something like `hosting-dev-hostname`.

**Comment by kevgo** [comment]
Decided to not make the `upstream` remote configurable for now because it would add complexity while there is no user demand for this. Will add when there is a demonstrated user need.

**Comment by kevgo** [comment]
This is now available in [Git Town 17](https://github.com/git-town/git-town/releases/tag/v17.0.0). Enjoy!

**Comment by ruudk** [comment]
> Yes, configuration can be per project. If you can't add a config file, for example because you work on a fork of an open-source project, you would (in the future) configure this in Git metadata:
> 
> ```
> git config git-town.remotes.dev fork
> ```

The correct way to do it is:

```
git config git-town.dev-remote fork
```


I just tested it and it works 🎉 Amazing 💙
