### ISSUE TITLE
ship-strategy fast-forward autocloses next PR

### ISSUE THREAD

**Issue by thatch** [git-town/git-town#4210]
### Steps to reproduce

Config: https://github.com/advice-animal/codemod-tox/blob/main/.git-branches.toml

pushed a pile of PRs, each stacked on the previous:
https://github.com/advice-animal/codemod-tox/pull/5 (parent main)
https://github.com/advice-animal/codemod-tox/pull/6 (parent 01-move-files-around)
https://github.com/advice-animal/codemod-tox/pull/7 (parent 02-simplify-api)

Tried to ship PR 5, which gave the following output:

### Command output

```shell
(.venv) [tim@tangerine codemod-tox]$ git checkout 01-move-files-around
Switched to branch '01-move-files-around'
Your branch is up to date with 'origin/01-move-files-around'.
(.venv) [tim@tangerine codemod-tox]$ git town ship

[01-move-files-around] git fetch --prune --tags

Looking for proposal online ... #6 (changefirst [2/7] Make API a bit more generic, mostly in ToxBase)

[01-move-files-around] git checkout main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.

Updating base branch of proposal #6 to 01-move-files-around ... ok

[main] git merge --ff-only 01-move-files-around
Updating 68dac65..9acddc8
Fast-forward
 codemod_tox/__init__.py                         |   6 +++++
 codemod_tox/base.py                             |  36 +++++++++++++++++++++++++++
 codemod_tox/{core.py => env.py}                 | 119 +++---------------------------------------------------------------------------------------
 codemod_tox/envlist.py                          |  62 +++++++++++++++++++++++++++++++++++++++++++++++
 codemod_tox/options.py                          |  36 +++++++++++++++++++++++++++
 tests/{test_core_env.py => test_env.py}         |   2 +-
 tests/{test_core_envlist.py => test_envlist.py} |   2 +-
 tests/{test_core_options.py => test_options.py} |   2 +-
 8 files changed, 146 insertions(+), 119 deletions(-)
 create mode 100644 codemod_tox/base.py
 rename codemod_tox/{core.py => env.py} (56%)
 create mode 100644 codemod_tox/envlist.py
 create mode 100644 codemod_tox/options.py
 rename tests/{test_core_env.py => test_env.py} (96%)
 rename tests/{test_core_envlist.py => test_envlist.py} (93%)
 rename tests/{test_core_options.py => test_options.py} (94%)

[main] git push
To github.com:advice-animal/codemod-tox
   68dac65..9acddc8  main -> main

[main] git push origin :01-move-files-around
To github.com:advice-animal/codemod-tox
 - [deleted]         01-move-files-around

[main] git branch -D 01-move-files-around
Deleted branch 01-move-files-around (was 9acddc8).


branch "02-simplify-api" is now a child of "main"
```

### Additional information

However, the push of the `:01-move-files-around` autoclosed the already-open https://github.com/advice-animal/codemod-tox/pull/6 since its parent went away.  I also tried to ship with 02 checked out earlier today and it said I had to ship 01 separately first.  Am I missing some repo config that makes this workflow possible?

**Comment by thatch** [comment]
I'm looking closer at the output, and see

```
Updating base branch of proposal #6 to 01-move-files-around ... ok
```

I wonder if that should say `to main`

**Comment by thatch** [comment]
Here's a screenshot of what the personal access token has:

![Screenshot 2024-11-11 at 8 21 21 PM](https://github.com/user-attachments/assets/8fdb48ca-55c0-498d-bd00-4cfe55eaf288)

**Comment by thatch** [comment]
Setting ship-delete-tracking-branch=false seems to be the solution here.  I don't see it actually changing the PR branch to merge into for subsequent PRs though?

**Comment by kevgo** [comment]
You are right that it should print `Updating base branch of proposal #6 to main ... ok`, and that's exactly the bug here. Will fix in the next release. Thanks for reporting this! :pray:
