### ISSUE TITLE
`git town aliases` isn't working

### ISSUE THREAD

**Issue by mklauer** [git-town/git-town#4295]
### Steps to reproduce

Follow the documentation https://www.git-town.com/all-commands.html?highlight=alias#git-town-installation

Execute

```
git town aliases
```

### Command output

```shell
Error: unknown command "aliases" for "git-town"
```

### Additional information

I'm using Git Town 16.7.0

**Comment by kevgo** [comment]
Thanks for reporting this! The website is outdated. Please use the [setup assistant](https://www.git-town.com/configuration) to set up aliases.
