### ISSUE TITLE
Feature request: Make selecting parent branch visually different than switching

### ISSUE THREAD

**Issue by lud-wj** [git-town/git-town#4340]
Hello,

I work on a lot of different repos, so sometimes I checkout branches that do not have a git town parent branch.

Then, when I call `git town switch`, Git Town displays a list of branches, and I select the one I want to work on ... except Git Town was acutally asking me for the parent of an unrelated branch.

I know it when Git Town asks me to select a branch again, which does not happen when switching in normal conditions. So I have to edit the git config to remove the `[git-town-branch ...]` entry, or change its parent.

When selecting a parent branch, Git Town displays a bold title when asking for a branch, and there is the `<none>` entry, plus number prefixes, etc., But those cases are rare and the brain is used to just focus on the blue list of available branches, and eager to select one and press enter.

Now I know this is just me not paying attention, so I would understand that you did nothing about it. But maybe I'm not alone.

What do you think about making those two branch selections visually different? For instance using yellow whenever git town displays a selection that is not the usual selection for the issued command ? (or just arbitrarily when asking to select a parent).

Or maybe prefix the branch names with `"use parent: "`, or display a border. something like that.

That could be something that we could opt-in as an accessibility setting.

**Comment by kevgo** [comment]
This is great feedback and I agree the issue needs to be addressed since it's too easy to mix up. We could also make `git town switch` not ask for parent branches at all. Simply display the branch hierarchy as it is right now. Branches without parents would be displayed as top-level branches. Git Town then asks for the parent when one syncs those branches.

**Comment by lud-wj** [comment]
Yes this would be actually much simpler :+1:

**Comment by kevgo** [comment]
This is now available in [Git Town 17.1](https://github.com/git-town/git-town/releases/tag/v17.1.0). Enjoy!

**Comment by lud-wj** [comment]
Thank you so much :)
