### ISSUE TITLE
Consider changing the config file name

### ISSUE THREAD

**Issue by stephenwade** [git-town/git-town#4343]
### Your message to us

Every time I want to open the Git&nbsp;Town config file, I keep looking for `.git-town.toml` and get confused for a moment until I remember that the file name is `.git-branches.toml`. It is also confusing for other team members who aren't familiar with Git&nbsp;Town, since only opening the file and reading the comments will explain its purpose.

Would you consider changing the config file name to `.git-town.toml`?

**Comment by stephenwade** [comment]
This doesn't have to be a breaking change if we support both filenames.

**Comment by kevgo** [comment]
The reasoning behind the current filename was that it provides generic information about Git branches, irrespective of whether Git Town is being used. Admittedly, that might have been a bit too ambitious. I'm open to supporting `.git-town.toml` as an alternative filename if that better fits your use case or resolves any concerns.

**Comment by kevgo** [comment]
This is now available in [Git Town 17.1](https://github.com/git-town/git-town/releases/tag/v17.1.0). Enjoy!
