### ISSUE TITLE
How to use git town observe ?

### ISSUE THREAD

**Issue by wayne-zhan** [git-town/git-town#4449]
### Your message to us

I try git town observe in vscode terminal. But I can't see anything change. How to use git town observe in vscode? Thank you

**Comment by stephenwade** [comment]
What observed branches are: https://www.git-town.com/branch-types#observed-branches

How to use the `git town observe` command: https://www.git-town.com/commands/observe

Do these pages answer your question?

**Comment by wayne-zhan** [comment]
Thank you！I have just found this article.
