### ISSUE TITLE
do a single push per command

### ISSUE THREAD

**Issue by charlierudolph** [git-town/git-town#620]
git push can be done from anywhere and do multiple things at once!

``` sh
# git ship
# push the master branch and remove the feature branch
git push origin master :feature

# git sync --all
# push all branches (works even for those without a remote)
git push origin master feature1 feature2 feature3
```

**Comment by kevgo** [comment]
If we can make this happen without error handling becoming more complicated, this would be an awesome improvement. Network requests are so slow!

**Comment by charlierudolph** [comment]
@kevgo started implementing this and it was easy for the initial direction, but is hard for the undo. Thoughts on updating to the following, the undo steps for a push command simply adds a push command to the other end of the step list.

**Comment by kevgo** [comment]
I'd say if this is a nice-to-have feature. If it ends up too complicated, or adds a lot of infrastructure to support this, then let's not do this at all. 

Having said that, the undo can be slow, so if the undo for a complex push command is several steps, that's totally acceptable.

**Comment by kevgo** [comment]
@charlierudolph okay to close this? It's ambitious, creates higher risk of inconsistent behavior in a lot of edge cases than benefits, and neither of us is going to get to implementing it.

**Comment by kevgo** [comment]
Ideas to make this simpler:
- move all pushes to the end of the StepList
- aggregate all pushes that are safe (we are sure they won't cause conflicts) in the StepList into one push command

**Comment by kevgo** [comment]
A challenge is that branches might get pushed some time after being synced locally. This would lead to possible conflicts if the tracking branch receives new commits in the meantime. It's a very small risk, though, so probably worth doing.

**Comment by kevgo** [comment]
Closing because this increases the risk of overwriting commits on the tracking branches, which would require complex logic to resolve and mitigate.
