### ISSUE TITLE
Request for a git-town in Scoop bucket extra 

### ISSUE THREAD

**Issue by Braunson** [git-town/git-town#639]
Would be nice for Window users to have a Scoop (Homebrew Windows Alternative) for Git-Town. 

i.e. placed in here.. https://github.com/lukesampson/scoop-extras

**Comment by kevgo** [comment]
I like the idea, thanks for the suggestion!

**Comment by smeijer** [comment]
Would be nice indeed. Anyone an idea how to get this running at Windows at all?

**Comment by kevgo** [comment]
I haven't tried it, but do the [manual installation instructions](http://www.git-town.com/install.html) work for you on Windows?

**Comment by smeijer** [comment]
Unfortunately not. I get the following exception.

running `git town` from a random git project:

```
c:\dev\my-project (develop)
$ git town
E:\utils\git-town\src\git-town: line 3: /c/dev/my-project/helpers/helpers.sh: No such file or directory
E:\utils\git-town\src\git-town: line 29: man: command not found
fatal: 'town' appears to be a git command, but we were not
able to execute it. Maybe git-town is broken?
```

When running from git-town src directory:

```
$ git town
grep: invalid option -- o
Usage: grep [OPTION]... PATTERN [FILE]...
Try `grep --help' for more information.
/e/utils/git-town/src/helpers/git_helpers/author_helpers.sh: line 33: conditional binary operator expected
/e/utils/git-town/src/helpers/git_helpers/author_helpers.sh: line 33: syntax error near `=~'
/e/utils/git-town/src/helpers/git_helpers/author_helpers.sh: line 33: `      if [[ $input =~ ^[0-9]+$ ]]; then'
/e/tools/cmder/vendor/git-town/src/helpers/git_helpers/branch_configuration_helpers.sh: line 155: conditional binary operator expected
....
```

**Comment by kevgo** [comment]
Alternative to #763

**Comment by kevgo** [comment]
We will get this for free with goreleaser, see #1379

**Comment by kevgo** [comment]
Related: #1479

**Comment by sheldonhull** [comment]
@kevgo did you say from this that gorelease supports scoop being a destination of the gate? I couldn't tell from my quick scan of goreleaseer if  was prebuilt for scoop already as a destination.

**Comment by kevgo** [comment]
I think so but haven't tried it yet: https://goreleaser.com/customization/scoop
