### ISSUE TITLE
Add more detailed explanation of commands to web site

### ISSUE THREAD

**Issue by kevgo** [git-town/git-town#684]
- horizontal menu bar with the GT commands
- click on the menu bar opens a vertical pane that lists all the Git commands that it runs
- hover over each Git command shows a pop-over that explains the command

![img_0072](https://cloud.githubusercontent.com/assets/268934/10472460/79e8a3ee-71d5-11e5-80b2-ac2559c096ad.JPG)

**Comment by allewun** [comment]
I like this

**Comment by charlierudolph** [comment]
Brillant!
