### ISSUE TITLE
Cannot continue after restoring open changes failed

### ISSUE THREAD

**Issue by kevgo** [git-town/git-town#708]
```
To abort, run "git hack --abort".
To continue after you have resolved the conflicts, run "git hack --continue".

~/foo > git hack --continue
/usr/local/Cellar/git-town/0.9.0/libexec/helpers/script_helpers.sh: line 27: continue_restore_open_changes: command not found
```

**Comment by charlierudolph** [comment]
`continue_restore_open_changes` should just drop an element from the stash as if popping results in a conflict, a copy of the stash stays in the list.

Related to #326. I remember trying fix this and being unable to reproduce it in our feature tests.
