### ISSUE TITLE
"git deliver" command

### ISSUE THREAD

**Issue by alexdavid** [git-town/git-town#715]
Git town has replaced a lot of the repeated low-level commands that git provides, but I still find myself having to do one workflow manually:

Suppose a project has a main development branch `master` and a perennial branch `production`. It is set up so CI automatically pushes to production when the `production` branch is updated.

Updating the perennial branch to the latest master requires the following workflow still:

``` shell
$ git stash
$ git checkout master
$ git sync
$ git checkout production
$ git pull
// Verify pull was a fast-forward
$ git merge master
// Verify that merge was a fast-forward
$ git push
$ git checkout [original branch name]
$ git stash pop
```

I would love a `git fast-forward-perennial [perennial-branch-name]` command that does this workflow for pushing the main development branch to the specified perennial branch.

This command should blow up if the pull or the merge were not a fast forwards, because it means someone screwed up and there are commits in the perennial branch not in master.

**Comment by kevgo** [comment]
Since this is for "delivering" larger bodies of work onto specific branches/environments, we could name this command `git deliver`. One would use it with the target branch name: `git deliver production`. Or to move a particular branch onto another branch: `git deliver qa production`.

**Comment by kevgo** [comment]
We don't want to evolve Git Town into a full-fledged release management solution, but there might be a small subset of commands might fit into its mission statement and current domain model. When running `git deliver`:

- it checks out the _delivery branch_
  - that's a new type of perennial branch, comparable to the _main development branch_
- it syncs the delivery branch with updates from the main development branch
  - how exactly this is done is configurable via a new `sync-delivery-strategy` config setting
  - possible values: `merge`, `rebase`, `fast-forward`
- it pushes the delivery branch to its remote
- deletes the local delivery branch if it didn't exist in the local workspace before

**Comment by kevgo** [comment]
A concern around this is that normal developers shouldn't be able to create new releases by merging commits into release branches. Release branches should be protected against accidental merges into them, because this causes changes to go out into production. So maybe the right way to make releases is through a pull request that only authorized people can merge?

**Comment by kevgo** [comment]
This concern can be addressed with a new config setting `deliver-strategy`. This setting defines how Git Town should merge the main branch into the delivery branch.

- `propose`: via a proposal, you choose the method in the web UI
- `ff-only`: via `git merge --ff-only`
- `no-ff`: via `git merge --no-ff`

**Comment by kevgo** [comment]
If this is creating releases, it might also have to create tags. Which is complex and somewhat orthogonal to Git Town's mission of managing branches.

Related: https://github.com/FollowTheProcess/tag.

**Comment by kevgo** [comment]
After careful consideration, I decided that this feature is out of scope for Git Town. While Git Town can assist with parts of the delivery process, like merging the dev branch into a "production" branch, it cannot handle the complexity required for actual software delivery in the real world. 

As an example, delivering Git Town's own codebase entails writing and reviewing release notes, running tools that gather statistics about the release, creating and pushing a Git tag, publishing a GitHub release, and then merging the `main` branch into the `public` branch. A `git town deliver` command could help only with the last of the listed activities. That's not enough.

Implementing the feature as outlined in this ticket would also conflict with best practices like protecting release branches from accidental local pushes.

Building more complex delivery capabilities into Git Town would result in two clusters of  distinct functionality with little overlap, which would feel duct-taped together. It's better to implement this as two separate tools.

With this in mind, I believe it’s best for Git Town to focus on its mission of making Git branches easy, and leave delivery to specialized tools.
