### ISSUE TITLE
Install via Chocolatey on Windows

### ISSUE THREAD

**Issue by kevgo** [git-town/git-town#763]
Similar to how Yarn does it: 
- configuration: https://github.com/yarnpkg/yarn/tree/master/resources/win-chocolatey
- build script: https://github.com/yarnpkg/yarn/blob/master/scripts/build-chocolatey.ps1

Alternative to #639

**Comment by nathunsmitty** [comment]
Hey @kevgo what's the status of this issue? I'm using Git Town on a team with some teammates on Windows machines and I'd love to give them an easy way to install it. Willing to tackle if no one else is working on it!

**Comment by kevgo** [comment]
Hey @nathunsmitty, we have no plans for working on this since we don't use Windows here. If you want to take a stab at it, please go ahead!

**Comment by sheldonhull** [comment]
I was looking for this as well, and maybe I could contribute something soon. 
Is there a consistent way to pull the most recent git release for windows via git api that you know of, or  a fixed path I could use? This would help windows developers setup be much simpler so I think it's worth contributing something on this. It's made my life better for sure!

**Comment by kevgo** [comment]
@sheldonhull http://github.com/Originate/git-town/releases/latest/download/git-town-windows-amd64.exe should give you the latest Windows binary

**Comment by kevgo** [comment]
We will get this for free with goreleaser, see #1379

**Comment by kevgo** [comment]
Goreleaser does this natively now: https://goreleaser.com/customization/chocolatey
