### ISSUE TITLE
verify configuration data 

### ISSUE THREAD

**Issue by kevgo** [git-town/git-town#969]
> When using Git Town with invalid configuration data
I want that Git Town points the issue out to me and aborts
So that it doesn't do bad things based on bad configuration data.

- simple configuration mistakes cause an error message and abort

```cucumber
Scenario: branch is configured as parent of itself
  Given I have a feature branch named "foo" as a child of "foo"
  And I am on the "foo" branch
  When I try to run `git sync`
  Then I get the error: 
    """
    Invalid branch parent found!
    Branch "master" is configured to have parent "master"
    """

**Comment by hammenm** [comment]
Maybe the issue can occur with other branch than master. In general it should check that a branch is not a parent of itself.
