### ISSUE TITLE
code hosting: implement missing API support for BitBucket

### ISSUE THREAD

**Issue by alexw10** [git-town/git-town#973]
I am not 100% sure this is a git town issue but was wondering if anyone has ideas.
We use a corporate bitbucket instance and when we do a 'git ship branchname' the PR that is associated with that get's marked as declined.
Anyone know how to put it in a state of "Merged"?
or any other ideas?

**Comment by charlierudolph** [comment]
`git ship` squash merges the branch which often loses the connection between the branch so it can't tell that the branch was squashed.

We are currently working on updating git ship to use the github api to merge pull requests (when applicable) and could do the same with bitbucket if it has an API that allows squash merging.

**Comment by alexw10** [comment]
That would be awesome, will this stay open and updated if you guys plan to do it?

**Comment by charlierudolph** [comment]
We don't currently have plans to implement it, but would definitely like it to be implemented. I'll update this issue once the github version is done and will be happy to help you or someone else implement it.

**Comment by charlierudolph** [comment]
So with 4.2.0 we introduced the ability to ship via the GitHub API. Shipping via the bitbucket API should now be relatively easy to add. The [bitbucket driver](https://github.com/Originate/git-town/blob/4cbd4d1cd32fe2b0aef9572de34d175bfa4817db/src/drivers/bitbucket.go) needs to implement `CanMergePullRequest` and `MergePullRequest`. Please see the GitHub example and its related tests. Implementing this requires writing some unit tests and then some manual testing. However it can reuse the infrastructure built to support the GitHub merging via the API

**Comment by alexw10** [comment]
Are you guys planning to implement the BitBucket part of it any time soon?

**Comment by alexw10** [comment]
Ah, actually after seeing looking a bit you added the bitbucket.go driver already and it just needs to be filled out with proper API calls etc right?

Might give this a shot one of these weekends but not sure when quite yet.

**Comment by alexw10** [comment]
Any update on this @kevgo ? 
Just curious if this is on your roadmap at all even.

**Comment by kevgo** [comment]
Anybody wanting to implement this: this shouldn't take more than an hour
- fill in the bodies for `SquashMergeProposal` and `UpdateProposalTarget` in https://github.com/git-town/git-town/blob/main/src/hosting/bitbucket/connector.go
- you can take the [GitHub connector](https://github.com/git-town/git-town/blob/main/src/hosting/github/connector.go) as a reference

**Comment by kevgo** [comment]
This is now available in [v16.3](https://github.com/git-town/git-town/releases/tag/v16.3.0).
