### ISSUE TITLE
git-sync: prevent testing deep stacks on CI

### ISSUE THREAD

**Issue by kevgo** [git-town/git-town#999]
When syncing a stack with many branches, it kicks off a CI test for each branch. This puts a lot of pressure on the CI server and discourages syncing.

It would be nice if Git Town would make it so that only the first N branches in a hierarchy get tested.

This is configurable via the `limit-testing` configuration option, which can be in the config file.

### "merge" sync strategy

- GitHub: Git Town appends `[ci skip]` to the merge commit message if needed

### "rebase" sync strategy

- GitHub: Git Town needs to add or remove `[ci skip]` to the commit messages in the branches

**Comment by kevgo** [comment]
On GitLab one can push using `-o ci.skip` ([docs](https://docs.gitlab.com/ee/user/project/push_options.html)).

**Comment by kevgo** [comment]
For GitHub: https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs

**Comment by stephenwade** [comment]
This seems outside the scope of Git Town. GitHub Actions can be configured to only run workflows on open PRs against a certain branch with the following configuration. I would be surprised if other CI providers didn't have similar configuration options.

```yaml
on:
  pull_request:
    branches:
      - main
```

(See also #3180)

**Comment by kevgo** [comment]
Good point that this is out of scope and should be addressed at the CI level. Closing this ticket.
